<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'rtl',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'ku',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 ڕۆژ',
	'1_MONTH'		=> '1 مانگ',
	'1_YEAR'		=> '1 ساڵ',
	'2_WEEKS'		=> '2 هەفتە',
	'3_MONTHS'		=> '3 مانگ',
	'6_MONTHS'		=> '6 مانگ',
	'7_DAYS'		=> '7 ڕۆژ',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'هەژمارەکەت پێشتر چاڵاککراوە',
	'ACCOUNT_DEACTIVATED'			=> 'هەژمارەکەت ڕاگیراوە و تەنها لەلایەن بەڕێوەبەرەوە دەکرێت هەژمارەکەت چاڵاک بکرێتەوە',
	'ACCOUNT_NOT_ACTIVATED'			=> 'تا ئێسا هەژمارەکەت چاڵاک نەکراوە',
	'ACP'							=> 'پەڕەی بەڕێوەبەرایەتی ',
	'ACP_SHORT'						=> 'پەڕەی بەڕێوەبەر',
	'ACTIVE'						=> 'چاڵاک',
	'ACTIVE_ERROR'					=> 'ناوی بەکارهێنەر ناچاڵاکە. ئەگەر کێشەت هەیە لە چۆنیەتی چاڵاککردنی هەژمار، تکایە پەیوەندی بە دەستەی بەڕێوەبەرانەوە بکە.',
	'ADMINISTRATOR'					=> 'بەڕێوەبەری گشتی',
	'ADMINISTRATORS'				=> 'بەڕێوەبەران',
	'AGE'							=> 'تەمەن',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX هەلەی',
	'AJAX_ERROR_TEXT'				=> 'هەلەیەک ڕوویدا لەکاتی جێ بەجێ کردنی داواکاریەکەت.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'داواکاریەکە ڕەتکرایەوە لەلایەن بەکارهێنەرەوە',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'ماوەی داواکاریەکەت تەواوبوو; تکایە دوبارە هەوڵبدەوە.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'هەلەیەک ڕویدا لەکاتی داواکاریەکەت، هەروەها ڕاژە وەڵامێکی نادروستی ناردەوە',
	'ALLOWED'						=> 'ڕێ پێدراو',
	'ALL_FILES'						=> 'سەرجەم پەڕگەکان',
	'ALL_FORUMS'					=> 'سەرجەم مەکۆکان',
	'ALL_MESSAGES'					=> 'سەرجەم پەیامەکان',
	'ALL_POSTS'						=> 'سەرجەم بەشدارییەکان',
	'ALL_TIMES'						=> 'هەموو کاتەکان %1$s %2$s ـن',
	'ALL_TOPICS'					=> 'سەرجەم بابەتەکان',
	'AND'							=> 'و',
	'ARE_WATCHING_FORUM'			=> 'بەژداریت کردووە کە ئاگادار بکرێیتەوە لە بوونی پەیامی نوێ لەم مەکۆیە.',
	'ARE_WATCHING_TOPIC'			=> 'بەژداریت کردووە کە ئاگادار بکرێیتەوە لە بوونی پەیامی نوێ لەم بابەتە.',
	'ASCENDING'						=> 'سەر بەرەوژوور',
	'ATTACHMENTS'					=> 'هاوپێچەکان',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'ئەو پەڕگەی وێنەیەی ویستت هاوپێچی بکەیت ناتەواوە.',
	'AUTHOR'						=> 'نووسەر',
	'AUTH_NO_PROFILE_CREATED'		=> 'دروستکردنی پڕۆفایلی بەکارهێنەر سەرکەوتوو نەبوو.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'سەرووشەی بنکەی زانیاری ناتەواوە.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'جۆری خزمەتگوزاری پێشکەشکراو بۆ یەکەی چارەسەری OAuth ناتەواوە.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'دروستکردنی خزمەتگوزاری OAuth جێ بەجێ نەکرا',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'نیشانەی OAuth پاشەکەوت نەکرا.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'نیشانەی OAuth بەشێوەیەکی هەلە پاشەکەوتکرا.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'بارکردنەکە پەسەند نەکرا، چونکە بارکراو پێ دەچێ پەڕگەیەکی زیان بەخش بێت',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'ئەم پەڕگەیە ناتوانرێت پیشان بدرێت چونکە پێوەکراوی <strong>%s</strong> ڕێ پێ نەدراوە .',
	'AVATAR_EMPTY_REMOTE_DATA'		=> ' وێنۆچکەی هەلبژێردراو ناتوانرێت باربکرێت، لەوانەیە هەلەیەک لە پەیوەندی کردن ڕویدابێت یان کار ناکات. تکایە دوبارە هەوڵبدە',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'ببورە هیچ وێنۆچکەیەکت بارنەکردووە',
	'AVATAR_INVALID_FILENAME'		=> '%s ناو پەڕگەیەکی تەواو نیە.',
	'AVATAR_NOT_UPLOADED'			=> 'نەتوانرا وێنۆچکە باربکرێت.',
	'AVATAR_NO_SIZE'				=> ' نەتوانرا پانیی یان بەرزیی وێنۆچکەی بەستەرکراو بپێورێت. تکایە خۆت بیانووسەوە.',
	'AVATAR_PARTIAL_UPLOAD'			=>  'پەڕگەی دیاریکراو بەش بەش بارکرا.',
	'AVATAR_PHP_SIZE_NA'			=> 'قەبارەی پەڕگەی وێنۆچکە زۆر گەورەیە.<br /> نەتوانرا گەورەترین قەبارەی ڕێپێدراو لە php.ini دیاریی بکرێت.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'قەبارەی پەڕگەی وێنۆچکە زۆر گەورەیە.<br /> گەورەترین قەبارەی ڕێپێدراوی بارکردن %1$d %2$s ـە.<br />تکایە سەرنجی ئەوە بدە ئەمە لە php.ini ڕێکخراوە و ناتوانرێت بگۆڕدرێت.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'نەتوانرا وێنۆچکەکە باربکرێت بەهۆی کێشەی پەیوەندیکردنەوە، تکایە دوبارە هەوڵبدەوە.',
	'AVATAR_URL_INVALID'			=> 'ئەو URL ـەی دیاریت کردووە نەگونجاوە.',
	'AVATAR_URL_NOT_FOUND'			=> 'نەتوانرا پەڕگەی دیاریکراو بدۆزرێتەوە',
	'AVATAR_WRONG_FILESIZE'			=> 'پێویستە قەبارەی وێنۆچکە لە نێوان 0 تا %1d %2s ـدا بێت.',
	'AVATAR_WRONG_SIZE'				=> 'وێنۆچکەی نێردراو %5$d خاڵ پانە و %6$d خاڵ بەرزە. پێویستە وێنۆچکە لانی کەم %1$d خاڵ پان بێت و %2$d خاڵ بەرز بێت، بەڵام زیاتر نەبێت لە %3$d خاڵ پانی و %4$d خاڵ بەرزی.',

	'BACK_TO_TOP'			=> 'لوتکە',
	'BACK_TO_PREV'			=> 'بگەڕێوە بۆ پەڕەی پێشوو',
	'BAN_TRIGGERED_BY_EMAIL'=> 'پۆستە ئەلیکترۆنیەکەت هاتە وەستاندن.',
	'BAN_TRIGGERED_BY_IP'	=> 'ناونیشانی ئای پی یەکەت هاتە وەستاندن.',
	'BAN_TRIGGERED_BY_USER'	=> 'ناوی بەکارهێنەریت هاتە وەستاندن.',
	'BBCODE_GUIDE'			=> 'ڕێبەریی BBCode',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'ڕۆژی لە دایک بوونەکان',
	'BOARD_BAN_PERM'		=> 'تۆ بە شێوەیەکی <strong>هەمیشەیی</strong> ڕاگیراویت لەم مەکۆیە.<br /><br />بۆ زانیاریی زیاتر تکایە پەیوەندی بە %2$sBoard Administrator%3$s ـەوە بکە.',
	'BOARD_BAN_REASON'		=> 'هۆکاری ڕاگرتن: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'تۆ لەم مەکۆیە ڕاگیراویت هەتا <strong>%1$s</strong>.<br /><br />بۆ زانیاریی زیاتر تکایە پەیوەندی بە %2$sBoard Administrator%3$s ـەوە بکە.',
	'BOARD_DISABLE'			=> 'ببورە بەڵام ئەم مەکۆیە لە ئێستادا ئامادە نییە.',
	'BOARD_DISABLED'		=> 'ئەم مەکۆیە لەکاتی ئێستادا ناچاڵاکە.',
	'BOARD_UNAVAILABLE'		=> 'ببورە، مەکۆ بە شێوەیەکی کاتی نائامادەیە، تکایە چەند خولەکێکی تر هەوڵ بدەوە.',
	'BROWSING_FORUM'		=> 'ئەو بەکارهێنەرانەی لەم مەکۆیەدان: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'ئەو بەکارهێنەرانەی لە مەکۆیەدان: %1$s و %2$d میوان',
		2	=> 'ئەو بەکارهێنەرانەی لە مەکۆیەدان: %1$s و %2$d میوان',
	),
	'BUTTON_EDIT'			=> 'دەسکاریکردن',
	'BUTTON_FORUM_LOCKED'	=> 'کلیلدراوە',
	'BUTTON_NEW_TOPIC'		=> 'بابەتی نوێ',
	'BUTTON_PM'				=> 'پەیامی تایبەت',
	'BUTTON_PM_FORWARD'		=> 'ئەنجامدان',
	'BUTTON_PM_NEW'			=> 'پەیامێکی تایبەتی نوێ',
	'BUTTON_PM_REPLY'		=> 'ناردنی وەڵام',
	'BUTTON_PM_REPLY_ALL'	=> 'وەڵامدانوەی هەمووان',
	'BUTTON_POST_REPLY'		=> 'زیادکردنی وەڵام',
	'BUTTON_QUOTE'			=> 'دەق',
	'BUTTON_TOPIC_LOCKED'	=> 'کلیلدراوە',
	'BYTES'					=> 'بایت',
	'BYTES_SHORT'			=> 'بایت',

	'CANCEL'				=> 'داخستن',
	'CHANGE'				=> 'گۆڕین',
	'CHANGE_FONT_SIZE'		=> 'گۆڕینی قەبارەی فۆنت',
	'CHANGING_PREFERENCES'	=> 'ڕێکخستنەکان دەگۆڕێت',
	'CHANGING_PROFILE'		=> 'ڕێکخستنەکانی پەڕگەی تایبەتی دەگۆڕێت',
	'CHARACTERS'			=> array(
		1	=> '%d نووسە',
		2	=> '%d نووسە',
	),
	'COLLAPSE_VIEW'			=>  'پێچانەوەی بینین',
	'CLOSE_WINDOW'			=> 'داخستنی پەنجەرە',
	'COLOUR_SWATCH'			=> 'پارچەی ڕەنگ',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'دڵنیابوون',
	'CONFIRM_CODE'			=> 'کۆدی دڵنیابوون',
	'CONFIRM_CODE_EXPLAIN'	=> 'کۆدەکە وەک خۆی بنووسەوە. پیتەکان هەستیار نین بەرانبەر گەورە و بچوکیی.',
	'CONFIRM_CODE_WRONG'	=> 'ئەو کۆدە دڵنیابوونەی نووسیوتە دروست نییە.',
	'CONFIRM_OPERATION'		=> 'دڵنیایت لە بە ئەنجام گەیاندنی ئەم کردەیە؟',
	'CONFIRM_AVATAR_DELETE' => 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت وێنۆچکە بسڕیتەوە؟',
	'CONGRATULATIONS'		=> 'پیرۆزبایی بۆ',
	'CONNECTION_FAILED'		=> 'پەیوەندی کردنەکە سەرکەوتوو نەبوو.',
	'CONNECTION_SUCCESS'	=> 'پەیوەندی کردنەکە سەرکەوتوبوو!',
	'CONTACT'				=> 'پەیوەندی',
	'CONTACT_USER'			=> 'پەیوەندی %s',
	'CONTACT_US'			=> 'پەیوەندیمان پێوە بکە',
	'COOKIES_DELETED'		=> 'هەموو کووکییەکانی مەکۆ بە سەرکەوتوویی سڕدرانەوە.',
	'CURRENT_TIME'			=> 'هەنووکە کات %s ـە',

	'DAY'					=> 'ڕۆژ',
	'DAYS'					=> 'ڕۆژ',
	'DELETE'				=> 'سڕینەوە',
	'DELETE_ALL'			=> 'سڕینەوەی هەموو',
	'DELETE_COOKIES'		=> 'هەموو کووکییەکانی مەکۆ بسڕەوە',
	'DELETE_MARKED'			=> 'نیشانەکراوەکان بسڕەوە',
	'DELETE_POST'			=> 'بەشدارییەکان بسڕەوە',
	'DELIMITER'				=> 'سنوردار',
	'DESCENDING'			=> 'سەر بەرەوخوار',
	'DISABLED'				=> 'ناچالاککراو',
	'DISPLAY'				=>  'پیشاندان',
	'DISPLAY_GUESTS'		=> 'میوانان پیشان بدە',
	'DISPLAY_MESSAGES'		=> 'پەیامەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_POSTS'			=> 'بەشدارییەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_TOPICS'		=> 'بابەتەکان لە پێشووەوە پیشان بدە',
	'DOWNLOADED'			=> 'داگیراو',
	'DOWNLOADING_FILE'		=> 'داگرتنی پەڕگە',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'تا ئێستا دانەگیراوە',
		1	=> '%d جار داگیراوە',
		2	=> '%d جار داگیراوە',
	),

	'EDIT_POST'							=> 'دەستکاریکردن',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> 'پۆستی ئەلیکترۆنی', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'پۆستی ئەلیکترۆنی',
	'EMAIL_INVALID_EMAIL'				=> 'ئەو پۆستە ئەلیکترۆنیەی نوسیوتە هەلەیە',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> '%2$s :وەڵام  <strong>%1$s هێڵی</strong> خرایەوە نێو کێشەکان ،ناردنی ئیمەیڵ لە',
	'EMPTY_SUBJECT'						=> 'پێویستە سەردێڕێک دیاری بکەیت کاتێک بابەتێکی نوێ دەنێریت.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'پێویستە سەردێڕێک دیاری بکەیت لە کاتی نووسینی پەیامێکی نوێدا.',
	'ENABLED'							=> 'چالاککراو',
	'ENCLOSURE'							=> 'پەرژینکردن',
	'ENTER_USERNAME'					=> 'ناوی بەکارهێنەر بنووسە',
	'ERR_CHANGING_DIRECTORY'			=> 'نەتوانرا بوخچە بگۆڕدرێت.',
	'ERR_CONNECTING_SERVER'				=> 'هەڵە ڕوویدا لە پەیوەندیکردن بە ڕاژەکارەوە.',
	'ERR_JAB_AUTH'						=> 'نەتوانرا ڕێگە پێبدرێت لە ڕاژەکاری جابەر.',
	'ERR_JAB_CONNECT'					=> 'نەتوانرا پەیوەندی بکرێت بە ڕاژەکاری جابەرەوە.',,
	'ERR_UNABLE_TO_LOGIN'				=> 'ناوی بەکارهێنەر یان تێپەڕەوشەی دیاریکراو نادروستە.',
	'ERR_UNWATCHING'					=> 'هەڵەیەک ڕوویدا لە کاتی هەوڵدان بۆ بەشداری نەکردن.',
	'ERR_WATCHING'						=>  'هەڵەیەک ڕوویدا لە کاتی هەوڵدان بۆ بەشداریکردن.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'وا دەردەکەوێت ڕێڕەوی دیاریکراوی phpBB نەگونجاو بێت.',
	'ERROR'									=> 'هەڵەیە',
	'EXPAND_VIEW'						=> 'فراوانکردنی بینین',
	'EXTENSION'							=> 'درێژکراوە',
	'EXTENSION_DISABLED'				=> 'درێژکراوەی <strong>%s</strong> چاڵاک نییە.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=>  'درێژکراوەی <strong>%s</strong> ناچالاککراوە و چیتر ناتوانرێت پیشان بدرێت.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'درێژکراوەی <strong>%s</strong> نەگونجاوە.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'					=> 'پ هـ د',
	'FAQ_EXPLAIN'			=> 'پرسیارە هەمیشە دووبارەکان',
	'FILENAME'				=> 'ناوی پەڕگە',
	'FILESIZE'				=> 'قەبارەی پەڕگە',
	'FILEDATE'				=> 'ڕێکەوتی پەڕگە',
	'FILE_COMMENT'			=> 'دەربارەی پەڕگە',
	'FILE_CONTENT_ERR'		=> 'نەتوانرا ناوەڕۆک بخوێندرێتەوە لە پەڕگە: %s',
	'FILE_JSON_DECODE_ERR'	=> 'کۆدهەڵوەشاندنەوەی پەڕگەی json سەرکەوتوو نەبوو: %s',
	'FILE_NOT_FOUND'		=> 'نەتوانرا پەڕگەی داواکراو بدۆزرێتەوە: %s',
	'FIND_USERNAME'			=> 'دۆزینەوەی ئەندام',
	'FOLDER'				=> 'بوخچە',
	'FORGOT_PASS'			=> 'تێپەڕەوشەم لەبیر چووە',
	'FORM_INVALID'			=> 'فۆڕمی نێردراو نەگونجاو بوو. جارێکی تر هەوڵی ناردنەوەی بدە',
	'FORUM'					=> 'مەکۆ',
	'FORUMS'				=> 'مەکۆکان',
	'FORUMS_MARKED'			=> 'هەموو مەکۆکان وەک خوێندراوە نیشانەکران.',
	'FORUM_CAT'				=> 'هاوپۆلی مەکۆ',
	'FORUM_INDEX'			=> 'دەستپێکی مەکۆ',
	'FORUM_LINK'			=> 'بەستەری مەکۆ',
	'FORUM_LOCATION'		=> 'شوێنی مەکۆ',
	'FORUM_LOCKED'			=> 'مەکۆ داخراوە',
	'FORUM_RULES'			=> 'یاساکانی مەکۆ',
	'FORUM_RULES_LINK'		=> 'تکایە کرتە لێرە بکە بۆ بینینی یاساکانی مەکۆ',
	'FROM'					=> ''لەلایەن',',
	'FSOCK_DISABLED'		=> 'نەتوانرا ئەو کردەیە بە ئەنجام بگەیەنرێت لەبەر ئەوەی فرمانی <var>fsockopen</var> ناچالاککراوە یان نەتوانراوە پرسی ڕاژەکار بدۆزرێتەوە.',
	'FSOCK_TIMEOUT'			=> 'لە ئەنجامی خوێندنەوەی زانیاری لە تۆڕ ، هەلەیەکی پەیوەندی کردن ڕویدا.',

	'FTP_FSOCK_HOST'				=> 'FTP خانەخوێ',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'ڕاژەکاری FTP بەکاربرا بۆ پەیوەندیکردن بە وێبگەکەتەوە.',
	'FTP_FSOCK_PASSWORD'			=> 'تێپەڕەوشەی FTP',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'تێپەڕەوشە بۆ بەکارهێنەری FTP ـیەکەت.',
	'FTP_FSOCK_PORT'				=> 'دەرچەی FTP',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'دەرچەی بەکارهێنراو بۆ پەیوەندی کردن بە ڕاژەرەکارەوە.',
	'FTP_FSOCK_ROOT_PATH'			=> 'ڕێڕەوی phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'ڕێڕەو لە ڕەگەوە بۆ مەکۆی phpBB ـیەکەت.',
	'FTP_FSOCK_TIMEOUT'				=> 'کاتی FTP تەواوبوو',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'ماوەی ئەو کاتە، بە چرکە، کە سیستەم چاوەڕێ دەکات بۆ وەڵامدانەوە لە ڕاژەکارەوە.',
	'FTP_FSOCK_USERNAME'			=> 'ناوی بەکارهێنەری FTP',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'ناوی بەکارهێنەر بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',

	'FTP_HOST'					=> 'خانەخوێی FTP',
	'FTP_HOST_EXPLAIN'			=> 'ڕاژەکاری FTP بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',
	'FTP_PASSWORD'				=> 'تێپەڕەوشەی FTP',
	'FTP_PASSWORD_EXPLAIN'		=> 'تێپەڕەوشە بۆ ناوی بەکاهێنەری FTP ـیەکەت.',
	'FTP_PORT'					=> 'دەرچەی FTP',
	'FTP_PORT_EXPLAIN'			=> 'دەرچەی بەکاربراوە بۆ پەیوەندیکردن بە ڕاژەکارەوە.',
	'FTP_ROOT_PATH'				=> 'ڕێڕەوی phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=>  'ڕێڕەو لە ڕەگەوە بۆ مەکۆی phpBB ـەکەت.',
	'FTP_TIMEOUT'				=> 'FTP کاتی تەواو بوو',
	'FTP_TIMEOUT_EXPLAIN'		=> 'ماوەی ئەو کاتە، بە چرکە، کە سیستەم چاوەڕێ دەکات بۆ وەڵامدانەوە لە ڕاژەکارەوە.',
	'FTP_USERNAME'				=> 'ناوی بەکارهێنەری FTP',
	'FTP_USERNAME_EXPLAIN'		=> 'ناوی بەکارهێنەر بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',

	'GENERAL_ERROR'				=> 'هەڵەیەکی گشتی',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> 'بڕۆ',
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'بڕۆ بۆ یەکەم بەشداری',
	'GOTO_LAST_POST'			=> 'بڕۆ بۆ دوایین بەشداری',
	'GOTO_PAGE'					=> 'بڕۆ بۆ پەڕەی',
	'GROUP'						=> 'گرووپ',
	'GROUPS'					=> 'گرووپەکان',
	'GROUP_ERR_TYPE'			=> 'جۆرێکی نەگونجاوی گرووپ دیاریکرا.',
	'GROUP_ERR_USERNAME'		=> 'ناوی هیچ گرووپێک دیاریی نەکراوە.',
	'GROUP_ERR_USER_LONG'		=> 'نابێت ناوی گرووپەکان لە 60 نووسە زیاتر بێت. ناوی گرووپی دیاریکراو زۆر درێژە.',
	'GUEST'						=> 'میوان',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> 'There is %d guest user online',
		2	=> 'There are %d guest users online',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d guest',
		2	=> '%d guests',
	),
	'G_ADMINISTRATORS'			=> 'Administrators',
	'G_BOTS'					=> 'Bots',
	'G_GUESTS'					=> 'Guests',
	'G_REGISTERED'				=> 'Registered users',
	'G_REGISTERED_COPPA'		=> 'Registered COPPA users',
	'G_GLOBAL_MODERATORS'		=> 'Global moderators',
	'G_NEWLY_REGISTERED'		=> 'Newly registered users',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d hidden user',
		2	=> '%d hidden users',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d hidden',
		2	=> '%d hidden',
	),
	'HIDE_GUESTS'					=> 'Hide guests',
	'HIDE_ME'						=> 'Hide my online status this session',
	'HOURS'							=> 'Hours',
	'HOME'							=> 'Home',

	'ICQ'						=> 'ICQ',
	'IF'						=> 'If',
	'IMAGE'						=> 'Image',
	'IMAGE_FILETYPE_INVALID'	=> 'Image file type %d for mimetype %s not supported.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Image file type mismatch: expected extension %1$s but extension %2$s given.',
	'IN'						=> 'in',
	'INDEX'						=> 'Index page',
	'INFORMATION'				=> 'Information',
	'INSECURE_REDIRECT'			=> 'Tried to redirect to potentially insecure url.',
	'INTERESTS'					=> 'Interests',
	'INVALID_DIGEST_CHALLENGE'	=> 'Invalid digest challenge.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> possibly an invalid email address?',
	'INVALID_PLURAL_RULE'		=> 'The chosen plural rule is invalid. Valid values are integers between 0 and 15.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> 'Your IP %1$s has been blocked because it is blacklisted. For details please see <a href="%2$s">%2$s</a>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Joined',
	'JUMP_PAGE'				=> 'Enter the page number you wish to go to',
	'JUMP_TO'				=> 'Jump to',
	'JUMP_TO_PAGE'			=> 'Jump to page',
	'JUMP_TO_PAGE_CLICK'	=> 'Click to jump to page…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'Last post',
	'LAST_UPDATED'						=> 'Last updated',
	'LAST_VISIT'						=> 'Last visit',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP extension not available.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Could not connect to LDAP server.',
	'LDAP_SEARCH_FAILED'				=> 'An error occurred while searching the LDAP directory.',
	'LEGEND'							=> 'Legend',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Live searches are not allowed.',
	'LOADING'							=> 'Loading',
	'LOCATION'							=> 'Location',
	'LOCK_POST'							=> 'Lock post',
	'LOCK_POST_EXPLAIN'					=> 'Prevent editing',
	'LOCK_TOPIC'						=> 'Lock topic',
	'LOGIN'								=> 'Login',
	'LOGIN_CHECK_PM'					=> 'Log in to check your private messages.',
	'LOGIN_CONFIRMATION'				=> 'Confirmation of login',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'To prevent brute forcing accounts the board requires you to enter a confirmation code after a maximum amount of failed logins. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to solve the CAPTCHA below.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'You have not been authenticated by Apache.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existant OAuth service has been requested.',
	'LOGIN_ERROR_PASSWORD'				=> 'You have specified an incorrect password. Please check your password and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'It was not possible to convert your password when updating this bulletin board’s software. Please %srequest a new password%s. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'You have specified an incorrect username. Please check your username and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_FORUM'						=> 'To view or post in this forum you must enter its password.',
	'LOGIN_INFO'						=> 'In order to login you must be registered. Registering takes only a few moments but gives you increased capabilities. The board administrator may also grant additional permissions to registered users. Before you register please ensure you are familiar with our terms of use and related policies. Please ensure you read any forum rules as you navigate around the board.',
	'LOGIN_VIEWFORUM'					=> 'The board requires you to be registered and logged in to view this forum.',
	'LOGIN_EXPLAIN_EDIT'				=> 'In order to edit posts in this forum you have to be registered and logged in.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'In order to view the online list you have to be registered and logged in.',
	'LOGIN_REQUIRED'					=> 'You need to login to perform this action.',
	'LOGOUT'							=> 'Logout',
	'LOGOUT_USER'						=> 'Logout [ %s ]',
	'LOG_ME_IN'							=> 'Remember me',

	'MAIN'					=> 'Main',
	'MARK'					=> 'Mark',
	'MARK_ALL'				=> 'Mark all',
	'MARK_ALL_READ'			=> 'Mark all read',
	'MARK_FORUMS_READ'		=> 'Mark forums read',
	'MARK_READ'				=> 'Mark read',
	'MARK_SUBFORUMS_READ'	=> 'Mark subforums read',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'Moderator Control Panel',
	'MCP_SHORT'				=> 'MCP',
	'MEMBERLIST'			=> 'Members',
	'MEMBERLIST_EXPLAIN'	=> 'View complete list of members',
	'MERGE'					=> 'Merge',
	'MERGE_POSTS'			=> 'Move posts',
	'MERGE_TOPIC'			=> 'Merge topic',
	'MESSAGE'				=> 'Message',
	'MESSAGES'				=> 'Messages',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d message',
		2	=> '%d messages',
	),
	'MESSAGE_BODY'			=> 'Message body',
	'MINUTES'				=> 'Minutes',
	'MODERATE'				=> 'Moderate',
	'MODERATOR'				=> 'Moderator',
	'MODERATORS'			=> 'Moderators',
	'MODULE_NOT_ACCESS'		=> 'Module not accessible',
	'MODULE_NOT_FIND'		=> 'Cannot find module %s',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Module file %s does not contain correct class [%s]',
	'MONTH'					=> 'Month',
	'MOVE'					=> 'Move',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'Our newest member <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'New message',
	'NEW_MESSAGES'				=> 'New messages',
	'NEW_POST'					=> 'New post',	// Not used anymore
	'NEW_POSTS'					=> 'New posts',	// Not used anymore
	'NEXT'						=> 'Next',		// Used in pagination
	'NEXT_STEP'					=> 'Next',
	'NEVER'						=> 'Never',
	'NO'						=> 'No',
	'NO_NOTIFICATIONS'			=> 'You have no notifications',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'You are not allowed to manage this group.',
	'NOT_AUTHORISED'			=> 'You are not authorised to access this area.',
	'NOT_WATCHING_FORUM'		=> 'You are no longer subscribed to updates on this forum.',
	'NOT_WATCHING_TOPIC'		=> 'You are no longer subscribed to this topic.',
	'NOTIFICATIONS'				=> 'Notifications',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>Reply</strong> from %1$s in bookmarked topic:',
	),
	'NOTIFICATION_FORUM'				=> '<em>Forum:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Group request</strong> from %1$s to join the group %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Group request approved</strong> to join the group %1$s.',
	'NOTIFICATION_PM'					=> '<strong>Private Message</strong> from %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Reply</strong> from %1$s in topic:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Post approved</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Post disapproved</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Post approval</strong> request by %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>Quoted</strong> by %1$s in:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>Reason:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Private Message reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>Post reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Report closed</strong> by %1$s for:',
	'NOTIFICATION_TOPIC'				=> '<strong>New topic</strong> by %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Topic approved</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Topic disapproved</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Topic approval</strong> request by %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notification type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>Activation required</strong> for newly registered user: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'others',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d others',
	),
	'NOTIFY_ADMIN'				=> 'Please notify the board administrator or webmaster.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Please notify the board administrator or webmaster: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'You are not allowed to access this file.',
	'NO_ACTION'					=> 'No action specified.',
	'NO_ADMINISTRATORS'			=> 'There are no administrators.',
	'NO_AUTH_ADMIN'				=> 'Access to the Administration Control Panel is not allowed as you do not have administrative permissions.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'You are not able to re-authenticate as a different user.',
	'NO_AUTH_OPERATION'			=> 'You do not have the necessary permissions to complete this operation.',
	'NO_AVATARS'				=> 'No avatars currently available',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Could not connect to smtp host : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'No birthdays today',
	'NO_EMAIL_MESSAGE'			=> 'Email message was blank.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Could not get mail server response codes.',
	'NO_EMAIL_SUBJECT'			=> 'No email subject specified.',
	'NO_FORUM'					=> 'The forum you selected does not exist.',
	'NO_FORUMS'					=> 'This board has no forums.',
	'NO_GROUP'					=> 'The requested usergroup does not exist.',
	'NO_GROUP_MEMBERS'			=> 'This group currently has no members.',
	'NO_IPS_DEFINED'			=> 'No IP addresses or hostnames defined',
	'NO_MEMBERS'				=> 'No members found for this search criterion.',
	'NO_MESSAGES'				=> 'No messages',
	'NO_MODE'					=> 'No mode specified.',
	'NO_MODERATORS'				=> 'There are no moderators.',
	'NO_NEW_MESSAGES'			=> 'No new messages',
	'NO_NEW_POSTS'				=> 'No new posts',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'No registered users',
	'NO_POSTS'					=> 'No posts',
	'NO_POSTS_TIME_FRAME'		=> 'No posts exist inside this topic for the selected time frame.',
	'NO_FEED_ENABLED'			=> 'Feeds are not available on this board.',
	'NO_FEED'					=> 'The requested feed is not available.',
	'NO_STYLE_DATA'				=> 'Could not get style data',
	'NO_SUBJECT'				=> 'No subject specified',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'The specified search backend doesn’t exist.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'No supported authentication methods.',
	'NO_TOPIC'					=> 'The requested topic does not exist.',
	'NO_TOPIC_FORUM'			=> 'The topic or forum no longer exists.',
	'NO_TOPICS'					=> 'There are no topics or posts in this forum.',
	'NO_TOPICS_TIME_FRAME'		=> 'No topics exist inside this forum for the selected time frame.',
	'NO_UNREAD_POSTS'			=> 'No unread posts',
	'NO_UPLOAD_FORM_FOUND'		=> 'Upload initiated but no valid file upload form found.',
	'NO_USER'					=> 'The requested user does not exist.',
	'NO_USERS'					=> 'The requested users do not exist.',
	'NO_USER_SPECIFIED'			=> 'No username was specified.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d attachment',
		2	=> '%d attachments',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'No posts in queue',		// 0
		1			=> '1 post in queue',		// 1
		2			=> '%d posts in queue',		// 2+
	),

	'OCCUPATION'				=> 'Occupation',
	'OFFLINE'					=> 'Offline',
	'ONLINE'					=> 'Online',
	'ONLINE_BUDDIES'			=> 'Online friends',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'In total there is <strong>%1$d</strong> user online :: %2$s and %3$s',
		2	=> 'In total there are <strong>%1$d</strong> users online :: %2$s and %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'In total there is <strong>%1$d</strong> user online :: %2$s, %3$s and %4$s',
		2	=> 'In total there are <strong>%1$d</strong> users online :: %2$s, %3$s and %4$s',
	),
	'OPTIONS'					=> 'Options',

	'PAGE_OF'				=> 'Page <strong>%1$d</strong> of <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Page %s',
	'PASSWORD'				=> 'Password',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d pixel',
		2	=> '%d pixels',
	),
	'PLAY_QUICKTIME_FILE'	=> 'Play Quicktime file',
	'PLEASE_WAIT'			=> 'Please wait.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'Click to view report',
	'POSTING_MESSAGE'		=> 'Posting message in %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Composing private message',
	'POST'					=> 'Post',
	'POST_ANNOUNCEMENT'		=> 'Announce',
	'POST_STICKY'			=> 'Sticky',
	'POSTED'				=> 'Posted',
	'POSTED_IN_FORUM'		=> 'in',
	'POSTED_ON_DATE'		=> 'on',
	'POSTS'					=> 'Posts',
	'POSTS_UNAPPROVED'		=> 'At least one post in this topic has not been approved.',
	'POSTS_UNAPPROVED_FORUM'=> 'At least one post in this forum has not been approved.',
	'POST_BY_AUTHOR'		=> 'by',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, who is currently on your ignore list, made this post.',
	'POST_DISPLAY'			=> '%1$sDisplay this post%2$s.',
	'POST_DAY'				=> '%.2f posts per day',
	'POST_DELETED_ACTION'	=> 'Deleted post:',
	'POST_DELETED'			=> 'This post has been deleted.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s for the following reason: %4$s',
	'POST_DETAILS'			=> 'Post details',
	'POST_NEW_TOPIC'		=> 'Post new topic',
	'POST_PCT'				=> '%.2f%% of all posts',
	'POST_PCT_ACTIVE'		=> '%.2f%% of user’s posts',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% of your posts',
	'POST_REPLY'			=> 'Post a reply',
	'POST_REPORTED'			=> 'Click to view report',
	'POST_SUBJECT'			=> 'Post subject',
	'POST_TIME'				=> 'Post time',
	'POST_TOPIC'			=> 'Post a new topic',
	'POST_UNAPPROVED_ACTION'	=> 'Post awaiting approval:',
	'POST_UNAPPROVED'		=> 'This post has not been approved.',
	'POWERED_BY'			=> 'Powered by %s',
	'PREVIEW'				=> 'Preview',
	'PREVIOUS'				=> 'Previous',		// Used in pagination
	'PREVIOUS_STEP'			=> 'Previous',
	'PRIVACY'				=> 'Privacy policy',
	'PRIVATE_MESSAGE'		=> 'Private message',
	'PRIVATE_MESSAGES'		=> 'Private messages',
	'PRIVATE_MESSAGING'		=> 'Private messaging',
	'PROFILE'				=> 'User Control Panel',

	'QUICK_LINKS'			=> 'Quick links',

	'RANK'						=> 'Rank',
	'READING_FORUM'				=> 'Viewing topics in %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Reading global announcement',
	'READING_LINK'				=> 'Following forum link %s',
	'READING_TOPIC'				=> 'Reading topic in %s',
	'READ_PROFILE'				=> 'Profile',
	'REASON'					=> 'Reason',
	'RECORD_ONLINE_USERS'		=> 'Most users ever online was <strong>%1$s</strong> on %2$s',
	'REDIRECT'					=> 'Redirect',
	'REDIRECTS'					=> 'Total redirects',
	'REGISTER'					=> 'Register',
	'REGISTERED_USERS'			=> 'Registered users:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'There is %1$d registered user and %2$s online',
		2	=> 'There are %1$d registered users and %2$s online',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d registered',
		2	=> '%d registered',
	),
	'REMOVE'					=> 'Remove',
	'REMOVE_INSTALL'			=> 'Please delete, move or rename the install directory before you use your board. If this directory is still present, only the Administration Control Panel (ACP) will be accessible.',
	'REPLIES'					=> 'Replies',
	'REPLY_WITH_QUOTE'			=> 'Reply with quote',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Replying to global announcement',
	'REPLYING_MESSAGE'			=> 'Replying to message in %s',
	'REPORT_BY'					=> 'Report by',
	'REPORT_POST'				=> 'Report this post',
	'REPORTING_POST'			=> 'Reporting post',
	'RESEND_ACTIVATION'			=> 'Resend activation email',
	'RESET'						=> 'Reset',
	'RESTORE_PERMISSIONS'		=> 'Restore permissions',
	'RETURN_INDEX'				=> '%sReturn to the index page%s',
	'RETURN_FORUM'				=> '%sReturn to the forum last visited%s',
	'RETURN_PAGE'				=> '%sReturn to the previous page%s',
	'RETURN_TOPIC'				=> '%sReturn to the topic last visited%s',
	'RETURN_TO'					=> 'Return to “%s”',
	'RETURN_TO_INDEX'			=> 'Return to Board Index',
	'FEED'						=> 'Feed',
	'FEED_NEWS'					=> 'News',
	'FEED_TOPICS_ACTIVE'		=> 'Active Topics',
	'FEED_TOPICS_NEW'			=> 'New Topics',
	'RULES_ATTACH_CAN'			=> 'You <strong>can</strong> post attachments in this forum',
	'RULES_ATTACH_CANNOT'		=> 'You <strong>cannot</strong> post attachments in this forum',
	'RULES_DELETE_CAN'			=> 'You <strong>can</strong> delete your posts in this forum',
	'RULES_DELETE_CANNOT'		=> 'You <strong>cannot</strong> delete your posts in this forum',
	'RULES_DOWNLOAD_CAN'		=> 'You <strong>can</strong> download attachments in this forum',
	'RULES_DOWNLOAD_CANNOT'		=> 'You <strong>cannot</strong> download attachments in this forum',
	'RULES_EDIT_CAN'			=> 'You <strong>can</strong> edit your posts in this forum',
	'RULES_EDIT_CANNOT'			=> 'You <strong>cannot</strong> edit your posts in this forum',
	'RULES_LOCK_CAN'			=> 'You <strong>can</strong> lock your topics in this forum',
	'RULES_LOCK_CANNOT'			=> 'You <strong>cannot</strong> lock your topics in this forum',
	'RULES_POST_CAN'			=> 'You <strong>can</strong> post new topics in this forum',
	'RULES_POST_CANNOT'			=> 'You <strong>cannot</strong> post new topics in this forum',
	'RULES_REPLY_CAN'			=> 'You <strong>can</strong> reply to topics in this forum',
	'RULES_REPLY_CANNOT'		=> 'You <strong>cannot</strong> reply to topics in this forum',
	'RULES_VOTE_CAN'			=> 'You <strong>can</strong> vote in polls in this forum',
	'RULES_VOTE_CANNOT'			=> 'You <strong>cannot</strong> vote in polls in this forum',

	'SEARCH'					=> 'Search',
	'SEARCH_MINI'				=> 'Search…',
	'SEARCH_ADV'				=> 'Advanced search',
	'SEARCH_ADV_EXPLAIN'		=> 'View the advanced search options',
	'SEARCH_KEYWORDS'			=> 'Search for keywords',
	'SEARCHING_FORUMS'			=> 'Searching forums',
	'SEARCH_ACTIVE_TOPICS'		=> 'Active topics',
	'SEARCH_FOR'				=> 'Search for',
	'SEARCH_FORUM'				=> 'Search this forum…',
	'SEARCH_NEW'				=> 'New posts',
	'SEARCH_POSTS_BY'			=> 'Search posts by',
	'SEARCH_SELF'				=> 'Your posts',
	'SEARCH_TOPIC'				=> 'Search this topic…',
	'SEARCH_UNANSWERED'			=> 'Unanswered posts',
	'SEARCH_UNREAD'				=> 'Unread posts',
	'SEARCH_USER_POSTS'			=> 'Search user’s posts',
	'SECONDS'					=> 'Seconds',
	'SEE_ALL'					=> 'See All',
	'SELECT'					=> 'Select',
	'SELECT_ALL_CODE'			=> 'Select all',
	'SELECT_DESTINATION_FORUM'	=> 'Please select a destination forum',
	'SELECT_FORUM'				=> 'Select a forum',
	'SEND_EMAIL'				=> 'Send email',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'Send email to %s',
	'SEND_PRIVATE_MESSAGE'		=> 'Send private message',
	'SETTINGS'					=> 'Settings',
	'SIGNATURE'					=> 'Signature',
	'SKIP'						=> 'Skip to content',
	'SKYPE'						=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP server does not support authentication.',
	'SORRY_AUTH_READ'			=> 'You are not authorised to read this forum.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'You are not authorised to download this attachment.',
	'SORT_BY'					=> 'Sort by',
	'SORT_JOINED'				=> 'Joined date',
	'SORT_LOCATION'				=> 'Location',
	'SORT_RANK'					=> 'Rank',
	'SORT_POSTS'				=> 'Posts',
	'SORT_TOPIC_TITLE'			=> 'Topic title',
	'SORT_USERNAME'				=> 'Username',
	'SPLIT_TOPIC'				=> 'Split topic',
	'SQL_ERROR_OCCURRED'		=> 'An SQL error occurred while fetching this page. Please contact the %sBoard Administrator%s if this problem persists.',
	'STATISTICS'				=> 'Statistics',
	'START_WATCHING_FORUM'		=> 'Subscribe forum',
	'START_WATCHING_TOPIC'		=> 'Subscribe topic',
	'STOP_WATCHING_FORUM'		=> 'Unsubscribe forum',
	'STOP_WATCHING_TOPIC'		=> 'Unsubscribe topic',
	'STRING_LIST_MULTI'			=> '%1$s, and %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s and %2$s',
	'SUBFORUM'					=> 'Subforum',
	'SUBFORUMS'					=> 'Subforums',
	'SUBJECT'					=> 'Subject',
	'SUBMIT'					=> 'Submit',

	'TB'				=> 'TB',
	'TERMS_USE'			=> 'Terms of use',
	'TEST_CONNECTION'	=> 'Test connection',
	'THE_TEAM'			=> 'The team',
	'TIB'				=> 'TiB',
	'TIME'				=> 'Time',
	'TIMEOUT_PROCESSING_REQ'			=> 'Request timed out.',

	'TOO_LARGE'						=> 'The value you entered is too large.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'The value of <strong>Maximum number of allowed recipients per private message</strong> setting you entered is too large.',

	'TOO_LONG'						=> 'The value you entered is too long.',

	'TOO_LONG_CONFIRM_CODE'			=> 'The confirm code you entered is too long.',
	'TOO_LONG_DATEFORMAT'			=> 'The date format you entered is too long.',
	'TOO_LONG_JABBER'				=> 'The Jabber account name you entered is too long.',
	'TOO_LONG_NEW_PASSWORD'			=> 'The password you entered is too long.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'The password confirmation you entered is too long.',
	'TOO_LONG_USER_PASSWORD'		=> 'The password you entered is too long.',
	'TOO_LONG_USERNAME'				=> 'The username you entered is too long.',
	'TOO_LONG_EMAIL'				=> 'The email address you entered is too long.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'You have tried to vote for too many options.',

	'TOO_SHORT'						=> 'The value you entered is too short.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'The confirm code you entered is too short.',
	'TOO_SHORT_DATEFORMAT'			=> 'The date format you entered is too short.',
	'TOO_SHORT_JABBER'				=> 'The Jabber account name you entered is too short.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'The password you entered is too short.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'The password confirmation you entered is too short.',
	'TOO_SHORT_USER_PASSWORD'		=> 'The password you entered is too short.',
	'TOO_SHORT_USERNAME'			=> 'The username you entered is too short.',
	'TOO_SHORT_EMAIL'				=> 'The email address you entered is too short.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'The email address confirmation you entered is too short.',
	'TOO_SMALL'						=> 'The value you entered is too small.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'The value of <strong>Maximum number of allowed recipients per private message</strong> setting you entered is too small.',

	'TOPIC'				=> 'Topic',
	'TOPICS'			=> 'Topics',
	'TOPICS_UNAPPROVED'	=> 'At least one topic in this forum has not been approved.',
	'TOPIC_ICON'		=> 'Topic icon',
	'TOPIC_LOCKED'		=> 'This topic is locked, you cannot edit posts or make further replies.',
	'TOPIC_LOCKED_SHORT'=> 'Topic locked',
	'TOPIC_MOVED'		=> 'Moved topic',
	'TOPIC_REVIEW'		=> 'Topic review',
	'TOPIC_TITLE'		=> 'Topic title',
	'TOPIC_UNAPPROVED'	=> 'This topic has not been approved.',
	'TOPIC_DELETED'		=> 'This topic has been deleted.',
	'TOTAL_ATTACHMENTS'	=> 'Attachment(s)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d log',
		2	=> '%d logs',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d private message in total',
		2	=> '%d private messages in total',
	),
	'TOPIC_POLL'		=> 'This topic has a poll.',
	'TOTAL_POSTS'		=> 'Total posts',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'Total posts <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'This topic has been reported',
	'TOTAL_TOPICS'		=> array(
		2	=> 'Total topics <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'Total members <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'Tracked PHP errors: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'It was not possible to determine the dimensions of the image. Please verify that the URL you entered is correct.',
	'UNABLE_TO_DELIVER_FILE'=> 'Unable to deliver file.',
	'UNKNOWN_BROWSER'		=> 'Unknown browser',
	'UNMARK_ALL'			=> 'Unmark all',
	'UNREAD_MESSAGES'		=> 'Unread messages',
	'UNREAD_POST'			=> 'Unread post',
	'UNREAD_POSTS'			=> 'Unread posts',
	'UNWATCH_FORUM_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this forum?',
	'UNWATCH_FORUM_DETAILED'	=> 'Are you sure you wish to unsubscribe from the forum “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this topic?',
	'UNWATCH_TOPIC_DETAILED'	=> 'Are you sure you wish to unsubscribe from the topic “%s”?',
	'UNWATCHED_FORUMS'			=> 'You are no longer subscribed to the selected forums.',
	'UNWATCHED_TOPICS'			=> 'You are no longer subscribed to the selected topics.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'You are no longer subscribed to the selected entries.',
	'UPDATE'				=> 'Update',
	'UPLOAD_IN_PROGRESS'	=> 'The upload is currently in progress.',
	'URL_REDIRECT'			=> 'If your browser does not support meta redirection %splease click HERE to be redirected%s.',
	'USERGROUPS'			=> 'Groups',
	'USERNAME'				=> 'Username',
	'USERNAMES'				=> 'Usernames',
	'USER_AVATAR'			=> 'User avatar',
	'USER_CANNOT_READ'		=> 'You cannot read posts in this forum.',
	'USER_POSTS'			=> array(
		1	=> '%d Post',
		2	=> '%d Posts',
	),
	'USERS'					=> 'Users',
	'USE_PERMISSIONS'		=> 'Test out user’s permissions',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more to be able to use this feature.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'Viewed',
	'VIEWED_COUNTS'		=> array(
		0	=> 'Not viewed yet',
		1	=> 'Viewed %d time',
		2	=> 'Viewed %d times',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'Viewing contact page',
	'VIEWING_FAQ'				=> 'Viewing FAQ',
	'VIEWING_MEMBERS'			=> 'Viewing member details',
	'VIEWING_ONLINE'			=> 'Viewing who is online',
	'VIEWING_MCP'				=> 'Viewing moderator control panel',
	'VIEWING_MEMBER_PROFILE'	=> 'Viewing member profile',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Viewing private messages',
	'VIEWING_REGISTER'			=> 'Registering account',
	'VIEWING_UCP'				=> 'Viewing user control panel',
	'VIEWS'						=> 'Views',
	'VIEW_BOOKMARKS'			=> 'View bookmarks',
	'VIEW_FORUM_LOGS'			=> 'View Logs',
	'VIEW_LATEST_POST'			=> 'View the latest post',
	'VIEW_NEWEST_POST'			=> 'View first unread post',
	'VIEW_NOTES'				=> 'View user notes',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'based on users active over the past %d minute',
		2	=> 'based on users active over the past %d minutes',
	),
	'VIEW_TOPIC'				=> 'خستنەڕووی بابەت',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'ڕاگەیاندن: ',
	'VIEW_TOPIC_GLOBAL'			=> 'ڕاگەیاندنی گشتی: ',
	'VIEW_TOPIC_LOCKED'			=> 'داخراوە: ',
	'VIEW_TOPIC_LOGS'			=> 'خستنەڕووی تۆمارەکان',
	'VIEW_TOPIC_MOVED'			=> 'گواستراوەتەوە: ',
	'VIEW_TOPIC_POLL'			=> 'ڕاپرسی: ',
	'VIEW_TOPIC_STICKY'			=> 'جێگیرکراو: ',
	'VISIT_WEBSITE'				=> 'سەردانکردنی وێبگە',

	'WARNINGS'			=> 'ئاگەدارییەکان',
	'WARN_USER'			=> 'ئاگەدارکردنەوەی ئەندام',
	'WATCH_FORUM_CONFIRM'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم مەکۆیە ؟',
	'WATCH_FORUM_DETAILED'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم مەکۆیە “%s”؟',
	'WATCH_TOPIC_CONFIRM'	=> 'ئایە تۆ دڵنیایت لە بەشداری کردنی ئەم بابەتە؟',
	'WATCH_TOPIC_DETAILED'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم بابەتە “%s”؟',
	'WELCOME_SUBJECT'	=> 'بەخێربێت بەڕێز %s ',
	'WEBSITE'			=> 'وێبگە',
	'WHOIS'				=> 'کێیە',
	'WHO_IS_ONLINE'		=> 'ئامادەبوانی ئێستا',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	=> 'تێپەڕەووشەی هەلەت نووسیوە',

	'WRONG_DATA_COLOUR'			=> 'بەهای ئەو ڕەنگەی نوسویتە تەواو نییە.',
	'WRONG_DATA_JABBER'			=> 'ئەو ناوەی نوسیوتە دروست نییە لە هەژماری Jabber.',
	'WRONG_DATA_LANG'			=> 'زمانی هەلبژێرداراو تەواو نییە.',
	'WRONG_DATA_POST_SD'		=> 'ڕێڕەوی ڕێکخستنی بەشدارییەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_POST_SK'		=> 'هەلبژاردنی ڕێکخستنی بەشدارییەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_TOPIC_SD'		=> 'ڕێڕەوی ڕێکخستنی بابەتەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_TOPIC_SK'		=> 'هەلبژاردنی ڕێکخستنی بابەتەکان کە دیارت کردبوو دروست نییە.',
	'WROTE'						=> 'نووسی',

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'				=> 'ساڵ',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> 'بەلێ',
	'YOU_LAST_VISIT'	=> 'دوایین سەرەدانت: %s',

	'datetime'			=> array(
		'TODAY'		=> 'ئەمڕۆ',
		'TOMORROW'	=> 'سبەی',
		'YESTERDAY'	=> 'دوێنی',
		'AGO'		=> array(
			0		=> 'کەمتر لە خولەکێک لەمەوبەر',
			1		=> '%d خولەک لەمەوبەر',
			2		=> '%d خولەک لەمەوبەر',
		),

		'Sunday'	=> 'یەک شەممە',
		'Monday'	=> 'دوو شەممە',
		'Tuesday'	=> 'سێ شەممە',
		'Wednesday'	=> 'چوار شەممە',
		'Thursday'	=> 'پێنج شەممە',
		'Friday'	=> 'هەینی',
		'Saturday'	=> ' شەممە',

		'Sun'		=> 'یەک شەممە',
		'Mon'		=> 'دوو شەممە',
		'Tue'		=> 'سێ شەممە',
		'Wed'		=> 'چوارشەممە',
		'Thu'		=> 'پێنچ شەممە',
		'Fri'		=> 'هەینی',
		'Sat'		=> 'شەممە',

		'January'	=> 'کانونی دووەم',
		'February'	=> 'شوبات',
		'March'		=> 'ئازار',
		'April'		=> 'نیسان',
		'May'		=> 'ئایار',
		'June'		=> 'حوزەیران',
		'July'		=> 'تەمموز',
		'August'	=> 'ئاب',
		'September' => 'ئەیلول',
		'October'	=> 'تشرینی یەکەم',
		'November'	=> 'تشرینی دووەم',
		'December'	=> 'کانونی یەکەم',

		'Jan'		=> 'کانونی دووەم',
		'Feb'		=> 'شوبات',
		'Mar'		=> 'ئازار',
		'Apr'		=> 'نیسان',
		'May_short'	=> 'ئایار',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'حوزەیران',
		'Jul'		=> 'تەمموز',
		'Aug'		=> 'ئاب',
		'Sep'		=> 'ئەیلول',
		'Oct'		=> 'تشرینی یەکەم',
		'Nov'		=> 'تشرینی دووەم',
		'Dec'		=> 'کانونی یەکەم',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'				=> '01 Jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
