<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
* @translated 2015 by [ SaM GoRaN, Sia Nariman, cutiyar ]
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'rtl',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'ku',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 ڕۆژ',
	'1_MONTH'		=> '1 مانگ',
	'1_YEAR'		=> '1 ساڵ',
	'2_WEEKS'		=> '2 هەفتە',
	'3_MONTHS'		=> '3 مانگ',
	'6_MONTHS'		=> '6 مانگ',
	'7_DAYS'		=> '7 ڕۆژ',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'هەژمارەکەت پێشتر چاڵاککراوە',
	'ACCOUNT_DEACTIVATED'			=> 'هەژمارەکەت ڕاگیراوە و تەنها لەلایەن بەڕێوەبەرەوە دەکرێت هەژمارەکەت چاڵاک بکرێتەوە',
	'ACCOUNT_NOT_ACTIVATED'			=> 'تا ئێسا هەژمارەکەت چاڵاک نەکراوە',
	'ACP'							=> 'پەڕەی بەڕێوەبەرایەتی ',
	'ACP_SHORT'						=> 'پەڕەی بەڕێوەبەر',
	'ACTIVE'						=> 'چاڵاک',
	'ACTIVE_ERROR'					=> 'ناوی بەکارهێنەر ناچاڵاکە. ئەگەر کێشەت هەیە لە چۆنیەتی چاڵاککردنی هەژمار، تکایە پەیوەندی بە دەستەی بەڕێوەبەرانەوە بکە.',
	'ADMINISTRATOR'					=> 'بەڕێوەبەری گشتی',
	'ADMINISTRATORS'				=> 'بەڕێوەبەران',
	'AGE'							=> 'تەمەن',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX هەلەی',
	'AJAX_ERROR_TEXT'				=> 'هەلەیەک ڕوویدا لەکاتی جێ بەجێ کردنی داواکاریەکەت.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'داواکاریەکە ڕەتکرایەوە لەلایەن بەکارهێنەرەوە',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'ماوەی داواکاریەکەت تەواوبوو; تکایە دوبارە هەوڵبدەوە.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'هەلەیەک ڕویدا لەکاتی داواکاریەکەت، هەروەها ڕاژە وەڵامێکی نادروستی ناردەوە',
	'ALLOWED'						=> 'ڕێ پێدراو',
	'ALL_FILES'						=> 'سەرجەم پەڕگەکان',
	'ALL_FORUMS'					=> 'سەرجەم مەکۆکان',
	'ALL_MESSAGES'					=> 'سەرجەم پەیامەکان',
	'ALL_POSTS'						=> 'سەرجەم بەشدارییەکان',
	'ALL_TIMES'						=> 'هەموو کاتەکان %1$s %2$s ـن',
	'ALL_TOPICS'					=> 'سەرجەم بابەتەکان',
	'AND'							=> 'و',
	'ARE_WATCHING_FORUM'			=> 'بەژداریت کردووە کە ئاگادار بکرێیتەوە لە بوونی پەیامی نوێ لەم مەکۆیە.',
	'ARE_WATCHING_TOPIC'			=> 'بەژداریت کردووە کە ئاگادار بکرێیتەوە لە بوونی پەیامی نوێ لەم بابەتە.',
	'ASCENDING'						=> 'سەر بەرەوژوور',
	'ATTACHMENTS'					=> 'هاوپێچەکان',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'ئەو پەڕگەی وێنەیەی ویستت هاوپێچی بکەیت ناتەواوە.',
	'AUTHOR'						=> 'نووسەر',
	'AUTH_NO_PROFILE_CREATED'		=> 'دروستکردنی پڕۆفایلی بەکارهێنەر سەرکەوتوو نەبوو.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'سەرووشەی بنکەی زانیاری ناتەواوە.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'جۆری خزمەتگوزاری پێشکەشکراو بۆ یەکەی چارەسەری OAuth ناتەواوە.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'دروستکردنی خزمەتگوزاری OAuth جێ بەجێ نەکرا',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'نیشانەی OAuth پاشەکەوت نەکرا.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'نیشانەی OAuth بەشێوەیەکی هەلە پاشەکەوتکرا.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'بارکردنەکە پەسەند نەکرا، چونکە بارکراو پێ دەچێ پەڕگەیەکی زیان بەخش بێت',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'ئەم پەڕگەیە ناتوانرێت پیشان بدرێت چونکە پێوەکراوی <strong>%s</strong> ڕێ پێ نەدراوە .',
	'AVATAR_EMPTY_REMOTE_DATA'		=> ' وێنۆچکەی هەلبژێردراو ناتوانرێت باربکرێت، لەوانەیە هەلەیەک لە پەیوەندی کردن ڕویدابێت یان کار ناکات. تکایە دوبارە هەوڵبدە',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'ببورە هیچ وێنۆچکەیەکت بارنەکردووە',
	'AVATAR_INVALID_FILENAME'		=> '%s ناو پەڕگەیەکی تەواو نیە.',
	'AVATAR_NOT_UPLOADED'			=> 'نەتوانرا وێنۆچکە باربکرێت.',
	'AVATAR_NO_SIZE'				=> ' نەتوانرا پانیی یان بەرزیی وێنۆچکەی بەستەرکراو بپێورێت. تکایە خۆت بیانووسەوە.',
	'AVATAR_PARTIAL_UPLOAD'			=>  'پەڕگەی دیاریکراو بەش بەش بارکرا.',
	'AVATAR_PHP_SIZE_NA'			=> 'قەبارەی پەڕگەی وێنۆچکە زۆر گەورەیە.<br /> نەتوانرا گەورەترین قەبارەی ڕێپێدراو لە php.ini دیاریی بکرێت.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'قەبارەی پەڕگەی وێنۆچکە زۆر گەورەیە.<br /> گەورەترین قەبارەی ڕێپێدراوی بارکردن %1$d %2$s ـە.<br />تکایە سەرنجی ئەوە بدە ئەمە لە php.ini ڕێکخراوە و ناتوانرێت بگۆڕدرێت.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'نەتوانرا وێنۆچکەکە باربکرێت بەهۆی کێشەی پەیوەندیکردنەوە، تکایە دوبارە هەوڵبدەوە.',
	'AVATAR_URL_INVALID'			=> 'ئەو URL ـەی دیاریت کردووە نەگونجاوە.',
	'AVATAR_URL_NOT_FOUND'			=> 'نەتوانرا پەڕگەی دیاریکراو بدۆزرێتەوە',
	'AVATAR_WRONG_FILESIZE'			=> 'پێویستە قەبارەی وێنۆچکە لە نێوان 0 تا %1d %2s ـدا بێت.',
	'AVATAR_WRONG_SIZE'				=> 'وێنۆچکەی نێردراو %5$d خاڵ پانە و %6$d خاڵ بەرزە. پێویستە وێنۆچکە لانی کەم %1$d خاڵ پان بێت و %2$d خاڵ بەرز بێت، بەڵام زیاتر نەبێت لە %3$d خاڵ پانی و %4$d خاڵ بەرزی.',

	'BACK_TO_TOP'			=> 'لوتکە',
	'BACK_TO_PREV'			=> 'بگەڕێوە بۆ پەڕەی پێشوو',
	'BAN_TRIGGERED_BY_EMAIL'=> 'پۆستە ئەلیکترۆنیەکەت هاتە وەستاندن.',
	'BAN_TRIGGERED_BY_IP'	=> 'ناونیشانی ئای پی یەکەت هاتە وەستاندن.',
	'BAN_TRIGGERED_BY_USER'	=> 'ناوی بەکارهێنەریت هاتە وەستاندن.',
	'BBCODE_GUIDE'			=> 'ڕێبەریی BBCode',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'ڕۆژی لە دایک بوونەکان',
	'BOARD_BAN_PERM'		=> 'تۆ بە شێوەیەکی <strong>هەمیشەیی</strong> ڕاگیراویت لەم مەکۆیە.<br /><br />بۆ زانیاریی زیاتر تکایە پەیوەندی بە %2$sBoard Administrator%3$s ـەوە بکە.',
	'BOARD_BAN_REASON'		=> 'هۆکاری ڕاگرتن: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'تۆ لەم مەکۆیە ڕاگیراویت هەتا <strong>%1$s</strong>.<br /><br />بۆ زانیاریی زیاتر تکایە پەیوەندی بە %2$sBoard Administrator%3$s ـەوە بکە.',
	'BOARD_DISABLE'			=> 'ببورە بەڵام ئەم مەکۆیە لە ئێستادا ئامادە نییە.',
	'BOARD_DISABLED'		=> 'ئەم مەکۆیە لەکاتی ئێستادا ناچاڵاکە.',
	'BOARD_UNAVAILABLE'		=> 'ببورە، مەکۆ بە شێوەیەکی کاتی نائامادەیە، تکایە چەند خولەکێکی تر هەوڵ بدەوە.',
	'BROWSING_FORUM'		=> 'ئەو بەکارهێنەرانەی لەم مەکۆیەدان: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'ئەو بەکارهێنەرانەی لە مەکۆیەدان: %1$s و %2$d میوان',
		2	=> 'ئەو بەکارهێنەرانەی لە مەکۆیەدان: %1$s و %2$d میوان',
	),
	'BUTTON_EDIT'			=> 'دەسکاریکردن',
	'BUTTON_FORUM_LOCKED'	=> 'کلیلدراوە',
	'BUTTON_NEW_TOPIC'		=> 'بابەتی نوێ',
	'BUTTON_PM'				=> 'پەیامی تایبەت',
	'BUTTON_PM_FORWARD'		=> 'ئەنجامدان',
	'BUTTON_PM_NEW'			=> 'پەیامێکی تایبەتی نوێ',
	'BUTTON_PM_REPLY'		=> 'ناردنی وەڵام',
	'BUTTON_PM_REPLY_ALL'	=> 'وەڵامدانوەی هەمووان',
	'BUTTON_POST_REPLY'		=> 'زیادکردنی وەڵام',
	'BUTTON_QUOTE'			=> 'دەق',
	'BUTTON_TOPIC_LOCKED'	=> 'کلیلدراوە',
	'BYTES'					=> 'بایت',
	'BYTES_SHORT'			=> 'بایت',

	'CANCEL'				=> 'داخستن',
	'CHANGE'				=> 'گۆڕین',
	'CHANGE_FONT_SIZE'		=> 'گۆڕینی قەبارەی فۆنت',
	'CHANGING_PREFERENCES'	=> 'ڕێکخستنەکان دەگۆڕێت',
	'CHANGING_PROFILE'		=> 'ڕێکخستنەکانی پەڕگەی تایبەتی دەگۆڕێت',
	'CHARACTERS'			=> array(
		1	=> '%d نووسە',
		2	=> '%d نووسە',
	),
	'COLLAPSE_VIEW'			=>  'پێچانەوەی بینین',
	'CLOSE_WINDOW'			=> 'داخستنی پەنجەرە',
	'COLOUR_SWATCH'			=> 'پارچەی ڕەنگ',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'دڵنیابوون',
	'CONFIRM_CODE'			=> 'کۆدی دڵنیابوون',
	'CONFIRM_CODE_EXPLAIN'	=> 'کۆدەکە وەک خۆی بنووسەوە. پیتەکان هەستیار نین بەرانبەر گەورە و بچوکیی.',
	'CONFIRM_CODE_WRONG'	=> 'ئەو کۆدە دڵنیابوونەی نووسیوتە دروست نییە.',
	'CONFIRM_OPERATION'		=> 'دڵنیایت لە بە ئەنجام گەیاندنی ئەم کردەیە؟',
	'CONFIRM_AVATAR_DELETE' => 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت وێنۆچکە بسڕیتەوە؟',
	'CONGRATULATIONS'		=> 'پیرۆزبایی بۆ',
	'CONNECTION_FAILED'		=> 'پەیوەندی کردنەکە سەرکەوتوو نەبوو.',
	'CONNECTION_SUCCESS'	=> 'پەیوەندی کردنەکە سەرکەوتوبوو!',
	'CONTACT'				=> 'پەیوەندی',
	'CONTACT_USER'			=> 'پەیوەندی %s',
	'CONTACT_US'			=> 'پەیوەندیمان پێوە بکە',
	'COOKIES_DELETED'		=> 'هەموو کووکییەکانی مەکۆ بە سەرکەوتوویی سڕدرانەوە.',
	'CURRENT_TIME'			=> 'هەنووکە کات %s ـە',

	'DAY'					=> 'ڕۆژ',
	'DAYS'					=> 'ڕۆژ',
	'DELETE'				=> 'سڕینەوە',
	'DELETE_ALL'			=> 'سڕینەوەی هەموو',
	'DELETE_COOKIES'		=> 'هەموو کووکییەکانی مەکۆ بسڕەوە',
	'DELETE_MARKED'			=> 'نیشانەکراوەکان بسڕەوە',
	'DELETE_POST'			=> 'بەشدارییەکان بسڕەوە',
	'DELIMITER'				=> 'سنوردار',
	'DESCENDING'			=> 'سەر بەرەوخوار',
	'DISABLED'				=> 'ناچالاککراو',
	'DISPLAY'				=>  'پیشاندان',
	'DISPLAY_GUESTS'		=> 'میوانان پیشان بدە',
	'DISPLAY_MESSAGES'		=> 'پەیامەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_POSTS'			=> 'بەشدارییەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_TOPICS'		=> 'بابەتەکان لە پێشووەوە پیشان بدە',
	'DOWNLOADED'			=> 'داگیراو',
	'DOWNLOADING_FILE'		=> 'داگرتنی پەڕگە',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'تا ئێستا دانەگیراوە',
		1	=> '%d جار داگیراوە',
		2	=> '%d جار داگیراوە',
	),

	'EDIT_POST'							=> 'دەستکاریکردن',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> 'پۆستی ئەلیکترۆنی', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'پۆستی ئەلیکترۆنی',
	'EMAIL_INVALID_EMAIL'				=> 'ئەو پۆستە ئەلیکترۆنیەی نوسیوتە هەلەیە',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> '%2$s :وەڵام  <strong>%1$s هێڵی</strong> خرایەوە نێو کێشەکان ،ناردنی ئیمەیڵ لە',
	'EMPTY_SUBJECT'						=> 'پێویستە سەردێڕێک دیاری بکەیت کاتێک بابەتێکی نوێ دەنێریت.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'پێویستە سەردێڕێک دیاری بکەیت لە کاتی نووسینی پەیامێکی نوێدا.',
	'ENABLED'							=> 'چالاککراو',
	'ENCLOSURE'							=> 'پەرژینکردن',
	'ENTER_USERNAME'					=> 'ناوی بەکارهێنەر بنووسە',
	'ERR_CHANGING_DIRECTORY'			=> 'نەتوانرا بوخچە بگۆڕدرێت.',
	'ERR_CONNECTING_SERVER'				=> 'هەڵە ڕوویدا لە پەیوەندیکردن بە ڕاژەکارەوە.',
	'ERR_JAB_AUTH'						=> 'نەتوانرا ڕێگە پێبدرێت لە ڕاژەکاری جابەر.',
	'ERR_JAB_CONNECT'					=> 'نەتوانرا پەیوەندی بکرێت بە ڕاژەکاری جابەرەوە.',
	'ERR_UNABLE_TO_LOGIN'				=> 'ناوی بەکارهێنەر یان تێپەڕەوشەی دیاریکراو نادروستە.',
	'ERR_UNWATCHING'					=> 'هەڵەیەک ڕوویدا لە کاتی هەوڵدان بۆ بەشداری نەکردن.',
	'ERR_WATCHING'						=>  'هەڵەیەک ڕوویدا لە کاتی هەوڵدان بۆ بەشداریکردن.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'وا دەردەکەوێت ڕێڕەوی دیاریکراوی phpBB نەگونجاو بێت.',
	'ERROR'									=> 'هەڵەیە',
	'EXPAND_VIEW'						=> 'فراوانکردنی بینین',
	'EXTENSION'							=> 'درێژکراوە',
	'EXTENSION_DISABLED'				=> 'درێژکراوەی <strong>%s</strong> چاڵاک نییە.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=>  'درێژکراوەی <strong>%s</strong> ناچالاککراوە و چیتر ناتوانرێت پیشان بدرێت.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'درێژکراوەی <strong>%s</strong> نەگونجاوە.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'					=> 'پ هـ د',
	'FAQ_EXPLAIN'			=> 'پرسیارە هەمیشە دووبارەکان',
	'FILENAME'				=> 'ناوی پەڕگە',
	'FILESIZE'				=> 'قەبارەی پەڕگە',
	'FILEDATE'				=> 'ڕێکەوتی پەڕگە',
	'FILE_COMMENT'			=> 'دەربارەی پەڕگە',
	'FILE_CONTENT_ERR'		=> 'نەتوانرا ناوەڕۆک بخوێندرێتەوە لە پەڕگە: %s',
	'FILE_JSON_DECODE_ERR'	=> 'کۆدهەڵوەشاندنەوەی پەڕگەی json سەرکەوتوو نەبوو: %s',
	'FILE_NOT_FOUND'		=> 'نەتوانرا پەڕگەی داواکراو بدۆزرێتەوە: %s',
	'FIND_USERNAME'			=> 'دۆزینەوەی ئەندام',
	'FOLDER'				=> 'بوخچە',
	'FORGOT_PASS'			=> 'تێپەڕەوشەم لەبیر چووە',
	'FORM_INVALID'			=> 'فۆڕمی نێردراو نەگونجاو بوو. جارێکی تر هەوڵی ناردنەوەی بدە',
	'FORUM'					=> 'مەکۆ',
	'FORUMS'				=> 'مەکۆکان',
	'FORUMS_MARKED'			=> 'هەموو مەکۆکان وەک خوێندراوە نیشانەکران.',
	'FORUM_CAT'				=> 'هاوپۆلی مەکۆ',
	'FORUM_INDEX'			=> 'دەستپێکی مەکۆ',
	'FORUM_LINK'			=> 'بەستەری مەکۆ',
	'FORUM_LOCATION'		=> 'شوێنی مەکۆ',
	'FORUM_LOCKED'			=> 'مەکۆ داخراوە',
	'FORUM_RULES'			=> 'یاساکانی مەکۆ',
	'FORUM_RULES_LINK'		=> 'تکایە کرتە لێرە بکە بۆ بینینی یاساکانی مەکۆ',
	'FROM'					=> 'لەلایەن',
	'FSOCK_DISABLED'		=> 'نەتوانرا ئەو کردەیە بە ئەنجام بگەیەنرێت لەبەر ئەوەی فرمانی <var>fsockopen</var> ناچالاککراوە یان نەتوانراوە پرسی ڕاژەکار بدۆزرێتەوە.',
	'FSOCK_TIMEOUT'			=> 'لە ئەنجامی خوێندنەوەی زانیاری لە تۆڕ ، هەلەیەکی پەیوەندی کردن ڕویدا.',

	'FTP_FSOCK_HOST'				=> 'FTP خانەخوێ',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'ڕاژەکاری FTP بەکاربرا بۆ پەیوەندیکردن بە وێبگەکەتەوە.',
	'FTP_FSOCK_PASSWORD'			=> 'تێپەڕەوشەی FTP',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'تێپەڕەوشە بۆ بەکارهێنەری FTP ـیەکەت.',
	'FTP_FSOCK_PORT'				=> 'دەرچەی FTP',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'دەرچەی بەکارهێنراو بۆ پەیوەندی کردن بە ڕاژەرەکارەوە.',
	'FTP_FSOCK_ROOT_PATH'			=> 'ڕێڕەوی phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'ڕێڕەو لە ڕەگەوە بۆ مەکۆی phpBB ـیەکەت.',
	'FTP_FSOCK_TIMEOUT'				=> 'کاتی FTP تەواوبوو',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'ماوەی ئەو کاتە، بە چرکە، کە سیستەم چاوەڕێ دەکات بۆ وەڵامدانەوە لە ڕاژەکارەوە.',
	'FTP_FSOCK_USERNAME'			=> 'ناوی بەکارهێنەری FTP',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'ناوی بەکارهێنەر بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',

	'FTP_HOST'					=> 'خانەخوێی FTP',
	'FTP_HOST_EXPLAIN'			=> 'ڕاژەکاری FTP بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',
	'FTP_PASSWORD'				=> 'تێپەڕەوشەی FTP',
	'FTP_PASSWORD_EXPLAIN'		=> 'تێپەڕەوشە بۆ ناوی بەکاهێنەری FTP ـیەکەت.',
	'FTP_PORT'					=> 'دەرچەی FTP',
	'FTP_PORT_EXPLAIN'			=> 'دەرچەی بەکاربراوە بۆ پەیوەندیکردن بە ڕاژەکارەوە.',
	'FTP_ROOT_PATH'				=> 'ڕێڕەوی phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=>  'ڕێڕەو لە ڕەگەوە بۆ مەکۆی phpBB ـەکەت.',
	'FTP_TIMEOUT'				=> 'FTP کاتی تەواو بوو',
	'FTP_TIMEOUT_EXPLAIN'		=> 'ماوەی ئەو کاتە، بە چرکە، کە سیستەم چاوەڕێ دەکات بۆ وەڵامدانەوە لە ڕاژەکارەوە.',
	'FTP_USERNAME'				=> 'ناوی بەکارهێنەری FTP',
	'FTP_USERNAME_EXPLAIN'		=> 'ناوی بەکارهێنەر بەکاربرا بۆ پەیوەندیکردن بە ڕاژەکارەکەتەوە.',

	'GENERAL_ERROR'				=> 'هەڵەیەکی گشتی',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> 'بڕۆ',
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'بڕۆ بۆ یەکەم بەشداری',
	'GOTO_LAST_POST'			=> 'بڕۆ بۆ دوایین بەشداری',
	'GOTO_PAGE'					=> 'بڕۆ بۆ پەڕەی',
	'GROUP'						=> 'گرووپ',
	'GROUPS'					=> 'گرووپەکان',
	'GROUP_ERR_TYPE'			=> 'جۆرێکی نەگونجاوی گرووپ دیاریکرا.',
	'GROUP_ERR_USERNAME'		=> 'ناوی هیچ گرووپێک دیاریی نەکراوە.',
	'GROUP_ERR_USER_LONG'		=> 'نابێت ناوی گرووپەکان لە 60 نووسە زیاتر بێت. ناوی گرووپی دیاریکراو زۆر درێژە.',
	'GUEST'						=> 'میوان',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> '%d بەکارهێنەری میوان لەسەر هێڵن',
		2	=> '%d بەکارهێنەری میوان لەسەر هێڵن',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d میوان',
		2	=> '%d میوان',
	),
	'G_ADMINISTRATORS'			=> 'بەڕێوەبەران',
	'G_BOTS'					=> 'بۆتەکان',
	'G_GUESTS'					=> 'میوانان',
	'G_REGISTERED'				=> 'بەکارهێنەرە خۆ تۆمارکردووەکان',
	'G_REGISTERED_COPPA'		=> 'بەکارهێنەرە خۆ تۆمارکردووەکانی COPPA',
	'G_GLOBAL_MODERATORS'		=> 'چاودێرە گشتییەکان',
	'G_NEWLY_REGISTERED'		=>  'بەکارهێنەرە خۆتۆمارکردووە نوێیەکان',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=>'%d بەکارهێنەری شارەوە لەسەر هێڵن',
		2	=> '%d بەکارهێنەری شارەوە لەسەر هێڵن',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d شاراوە',
		2	=> '%d شاراوە',
	),
	'HIDE_GUESTS'					=>  'میوانان بشارەوە',
	'HIDE_ME'						=> 'دۆخی سەرهێڵیم بشارەوە لەم دانیشتنە.',
	'HOURS'							=> 'کاژێر',
	'HOME'							=> 'ماڵەوە',

	'ICQ'						=> 'ICQ',
	'IF'						=> 'ئەگەر',
	'IMAGE'						=> 'وێنە',
	'IMAGE_FILETYPE_INVALID'	=> 'پاڵپشت نەکراوە %s بۆ مایمجۆر %d پەڕگەی وێنە جۆری',
	'IMAGE_FILETYPE_MISMATCH'	=> 'بەڵام گەیەنەری  %2$s دراوە %1$s پەڕگەی وێنە جۆری بزرگونجاو گەیەنەری چاوەڕوانکراو',
	'IN'						=> 'لە',
	'INDEX'						=> 'دەستپێک',
	'INFORMATION'				=> 'زانیاریی',
	'INSECURE_REDIRECT'			=> 'هەوڵدان بۆ کردنەوەی بەستەر سەرکەوتوو نەبوو.',
	'INTERESTS'					=> 'ئارەزووەکان',
	'INVALID_DIGEST_CHALLENGE'	=> 'ڕێ پێ نەدراوە digest challenge.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> لەوەدەچێت ناونیشانی پۆستی ئەلیکترۆنی نادروست بێت؟',
	'INVALID_PLURAL_RULE'		=> 'بنکەی کۆکردنەوەی هەڵبژێردراو دروست نییە، بەهای دروست بریتییە لە ژمارەکانی نێوان 0 و 15 .',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=>  'IP ـیەکەت %1$s قەدەغەکراوە لەبەر ئەوەی کراوەتە لیستی ڕەشەوە. بۆ وردەکاریی زیاتر تکایە <a href="%2$s">%2$s</a> ببینە.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'بەشدارە لە',
	'JUMP_PAGE'				=> 'ژمارەی ئەو پەڕەیە بنووسە کە دەتەوێت بڕۆی بۆی.',
	'JUMP_TO'				=> 'گواستنەوە بۆ',
	'JUMP_TO_PAGE'			=> 'کرتە بکە بۆ گواستنەوە بۆ پەڕە',
	'JUMP_TO_PAGE_CLICK'	=> 'کرتە بکە بۆ گواستنەوە بۆ پەڕە...',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'دوایین پەیام',
	'LAST_UPDATED'						=> 'دوایین نوێکردنەوە',
	'LAST_VISIT'						=> 'دوایین سەرەدان',
	'LDAP_NO_LDAP_EXTENSION'			=> 'درێژکراوەی LDAP نییە.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'نەتوانرا پەیوەندی بکرێت بە ڕاژەکاری LDAP ـیەوە.',
	'LDAP_SEARCH_FAILED'				=> 'LDAP هەڵەیەک ڕوویدا لەکاتی گەڕان بۆ شوێنی',
	'LEGEND'							=> 'ڕەنگی گرووپەکان',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'گەڕانی زیندو ڕێگەی پێ نەدراوە.',
	'LOADING'							=> 'ئامادەکردن',
	'LOCATION'							=> 'شوێن',
	'LOCK_POST'							=> 'داخستنی پەیام',
	'LOCK_POST_EXPLAIN'					=> 'قەدەغەکردنی دەستکاریکردن',
	'LOCK_TOPIC'						=> 'داخستنی بابەت',
	'LOGIN'								=> 'چوونەژوورەوە',
	'LOGIN_CHECK_PM'					=>'بڕۆ ژوورەوە بۆ بینینی پەیامە تایبەتییەکانت.',
	'LOGIN_CONFIRMATION'				=>  'بۆ بەدوورگرتنی هێرشی سەر هەژمارەکەت ،تەختاییەکە داوای کۆدی زانیاریت لێ دەکات لەدوای ژمارەیەکی زۆر لە سەرنەوکەوتن لە هاتنە ژوورەوە ،کۆدی دڵنیایی لە خوارەوە دەبێت',  // unused
	'LOGIN_ERROR_ATTEMPTS'				=>  'تۆ زۆرترین ژمارەت تێپەڕاند لە هەوڵدان بۆ هاتنە ژوورەوە ،وا داوادەکرێ کۆدی دڵنیایی بەکارببەیت بۆ بەردەوامبوون',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=>  'نەسەلمێندراویت لەلایەن Apache ـیەوە.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'خزمەتگوزاری OAuth داواکراو بەردەست نییە.',
	'LOGIN_ERROR_PASSWORD'				=>  'تێپەڕەوشەیەکی نادروستت نووسی. تکایە لە تێپەڕەوشەکە دڵنیابە و هەوڵبدەوە. گەر هەر بەردەوامبوویت لە هەبوونی کێشە تکایە پەیوەندی بکە بە %sبەڕێوەبەری مەکۆ%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'لە توانادا نەبوو کە تێپەڕەوشەکەت بگۆڕدرێت لە کاتی نوێکردنەوەی وەشانی مەکۆدا. تکایە %sداوای تێپەڕەوشەیەکی نوێ بکە%s. گەر هەر بەردەوامبوویت لە هەبوونی کێشە تکایە پەیوەندی بکە بە %sبەڕێوەبەری مەکۆ%s.',
	'LOGIN_FORUM'						=> 'بۆ بینین و ناردنی پەیام لەم مەکۆیەدا پێویستە تێپەڕەوشەی مەکۆ بنووسیت',
	'LOGIN_INFO'						=> 'بۆ ئەوەی بچیتە ژوورەوە پێویستە خۆت تۆمار کردبێت. خۆتۆمارکردن چەند ساتێکی کەمی دەوێت بەڵام دەسەڵاتی زیاترت پێ دەدات. دەشێت بەڕێوەبەری مەکۆ دەسەڵاتی زیادە ببەخشێت بە بەکارهێنەرە تۆماربووەکان. پێش ئەوەی خۆت تۆمار بکەیت تکایە دڵنیابە لەوەی ڕەزامەندیت لەسەر مەرجەکانی بەکارهێنان. تکایە دڵنیابە لەوەی کە یاسای هەر مەکۆیەک دەخوێنیتەوە کاتێک سەردانیان دەکەیت.',
	'LOGIN_VIEWFORUM'					=> 'مەکۆ پێویستی بەوەیە کە خۆت تۆمار کردبێت و لە ژوورەوە بیت تا بتوانی بیبینیت.',
	'LOGIN_EXPLAIN_EDIT'				=> 'بۆ ئەوەی دەستکاری پەیامەکانی ئەم مەکۆیە بکەیت  پێویستە خۆت تۆمار کردبێت و لە ژوورەوە بیت.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'بۆ ئەوەی لیستی ئەوانە ببینیت کە لەسەر هێڵن پێویستە خۆت تۆمار کردبێت و لە ژوورەوە بیت.',
	'LOGIN_REQUIRED'					=> 'پێویستە بچیتە ژوورەوە تا بتوانی ئەم کردەیە جێ بەجێ بکەیت.',
	'LOGOUT'							=> 'دەرچوون',
	'LOGOUT_USER'						=> 'دەرچوون [ %s ]',
	'LOG_ME_IN'							=> 'بەبیرم بێنەوە',

	'MAIN'					=> 'دەستپێک',
	'MARK'					=> 'نیشانەکردن',
	'MARK_ALL'				=> 'نیشانەکردنی هەموو',
	'MARK_ALL_READ'			=> 'هەموویان وەک خوێندراو دیاربکە',
	'MARK_FORUMS_READ'		=> 'مەکۆکان وەک خوێندراو دیاربکە',
	'MARK_READ'				=> 'وەک خوێندراو دیار بکە',
	'MARK_SUBFORUMS_READ'	=> 'ژێر مەکۆکان وەک خوێندراو دیاربکە',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'پەڕەی چاودێر',
	'MCP_SHORT'				=> 'پەڕەی چاودێر',
	'MEMBERLIST'			=> 'ئەندامان',
	'MEMBERLIST_EXPLAIN'	=> 'لیستی تەواوەتی ئەندامان ببینە',
	'MERGE'					=> 'لکاندن',
	'MERGE_POSTS'			=> 'لکاندنی بەشدارییەکان',
	'MERGE_TOPIC'			=> 'لکاندنی بابەتەکان',
	'MESSAGE'				=> 'پەیام',
	'MESSAGES'				=> 'پەیامەکان',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d پەیام',
		2	=> '%d پەیام',
	),
	'MESSAGE_BODY'			=> 'ناوەڕۆکی پەیام',
	'MINUTES'				=> 'خولەک',
	'MODERATE'				=> 'چاودێری',
	'MODERATOR'				=> 'چاودێر',
	'MODERATORS'			=> 'چاودێران',
	'MODULE_NOT_ACCESS'		=> 'Module بەردەست نییە',
	'MODULE_NOT_FIND'		=> 'نەتوانرا module %s بدۆزرێتەوە',
	'MODULE_FILE_INCORRECT_CLASS'	=>'پەڕگەی module %s گۆڕاوی دروستی تێدا نییە [%s]',
	'MONTH'					=> 'مانگ',
	'MOVE'					=> 'گواستنەوە',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'نوێترین ئەندام <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'پەیامی نوێ',
	'NEW_MESSAGES'				=> 'پەیامی نوێ',
	'NEW_POST'					=> 'بەشداری نوێ',	// Not used anymore
	'NEW_POSTS'					=> 'بەشداری نوێ',	// Not used anymore
	'NEXT'						=> 'داهاتوو',		// Used in pagination
	'NEXT_STEP'					=> 'داهاتوو',
	'NEVER'						=> 'هەرگیز',
	'NO'						=> 'نەخێر',
	'NO_NOTIFICATIONS'			=> 'هیچ ئاگەدارکردنەوەیەکت نییە',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'تۆ ڕێگەت پێ نەدراوە بۆ چاودێریکردنی ئەم گرووپە.',
	'NOT_AUTHORISED'			=> 'دەسەڵاتی هاتنە ئەم شوێنەت نییە.',
	'NOT_WATCHING_FORUM'		=> 'چیتر تۆ بەشدار نیت لە نوێکارییەکانی ئەم مەکۆیە.',
	'NOT_WATCHING_TOPIC'		=> 'چیتر تۆ بەشدار نیت لەم بابەتە.',
	'NOTIFICATIONS'				=> 'وریاکەرەوەکان',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong> وەڵامی نوێ</strong>  لە %1 $s لەبابەتی دڵخواز:',
	),
	'NOTIFICATION_FORUM'				=> '<em>مەکۆ:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>داوای بەئەندامبوون دەکات</strong>  لە %1 $s لە گرووپی %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>داواکاریەکەت بۆ ئەندامێتی پەسەندکرا ب</strong> لە گرووپی %1$s.',
	'NOTIFICATION_PM'					=> '<strong>پەیامی تایبەتی</strong> لە %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>وەڵامێکی نوێ</strong> لە %1$s لەبابەتی:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>بەشدارییەکە پەسەندکرا</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>بەشدارییەکە پەسەند نەکرا</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>پەسەندکرانی بەشداری</strong>داواکراوە لەلایەن %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>بەشدارییەکەت دەق کرا </strong> لەلایەن %1$s لە:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>هۆکار:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>ئاگەداری لەپەیامی تایبەتی</strong> لەلایەن %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>ئاگەداری لە بەشداری</strong> لەلایەن %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>ئاگەدارکردنەوە داخراوە</strong> لەلایەن %1$s بۆ:',
	'NOTIFICATION_TOPIC'				=> '<strong>بابەتی نوێ</strong> لەلایەن %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>بابەت پەسەندکرا</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>بابەت پەسەند نەکرا</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>بابەت پەسەندکردن</strong> داواکراوە لەلایەن %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'جۆری ئاگەدارکەرەوە "%s"  لە پەڕگەی سیستەم لەدەست دراوە.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>چاڵاککردن پێویستە</strong> بۆ ئەندامە تۆماربووە نوێیەکان: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'ئەوانی تر',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d ئەوانی تر',
	),
	'NOTIFY_ADMIN'				=> 'تکایە بەڕێوەبەری یان چاودێران ئاگەداربکەوە.',
	'NOTIFY_ADMIN_EMAIL'		=> 'تکایە بەڕێوەبەر یان چاودێران ئاگەدار بکەوە: <a href="بۆ:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'تۆ ڕێگەت پێ نەدراوە بۆ داگرتنی ئەم پەڕگەیە.',
	'NO_ACTION'					=> 'هیچ هەلبژاردنێک نیشانە نەرکاوە.',
	'NO_ADMINISTRATORS'			=> 'هیچ بەڕێوەبەرێک نییە لەم مەکۆیە.',
	'NO_AUTH_ADMIN'				=> 'چوونە ناو کۆنترۆڵ پانێڵ ڕێ پێ نەدراوە لەبەر ئەوەی دەسەڵاتەکانی بەڕێوەبەریت نییە.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'ناتوانیت خۆت بسەلمێنیتەوە وەک بەکارهێنەرێکی جیاواز.',
	'NO_AUTH_OPERATION'			=>  'دەسەڵاتی پێویستت نییە بۆ بە ئەنجام گەیاندنی ئەم کردەیە.',
	'NO_AVATARS'				=> 'هیچ وێنۆچکەیەک بوونی نییە',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'نەتوانرا پەیوەندی بکات بە خانەخوێی smtp ـیەوە : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'هیچ ڕۆژێکی لە دایکبوون نییە ئەمڕۆ.',
	'NO_EMAIL_MESSAGE'			=> 'پەیامی ئەلیکترۆنی بەتالە.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'نەتوانرا کۆدەکانی وەڵامی ڕاژەکاری پۆستی ئەلیکترۆنی بەدەست بهێنێت.',
	'NO_EMAIL_SUBJECT'			=> 'سەردیڕ نەنووسراوە.',
	'NO_FORUM'					=> 'مەکۆی نیشانە کراوە بوونی نییە.',
	'NO_FORUMS'					=> 'ئەم سەکۆیە هیچ مەکۆیەکی تێدا نییە.',
	'NO_GROUP'					=> 'گرووپی بەکارهێنەری داواکراو بوونی نییە.',
	'NO_GROUP_MEMBERS'			=> 'هەنووکە ئەم گرووپە هیچ ئەندامێکی تیادا نییە.',
	'NO_IPS_DEFINED'			=> 'هیچ ناونیشانێکی IP یان ناوی خانەخوێیەک دیاریی نەکراوە',
	'NO_MEMBERS'				=> 'هیچ ئەندامێک نەدۆزرایەوە بۆ ئەم گەڕانە',
	'NO_MESSAGES'				=> 'پەیام نییە',
	'NO_MODE'					=> 'هیچ شێوازێک دیاریی نەکراوە',
	'NO_MODERATORS'				=> 'هیچ چاودێرێک نییە',
	'NO_NEW_MESSAGES'			=> 'پەیامی نوێ نییە',
	'NO_NEW_POSTS'				=> 'بەشداری نوێ نییە',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'هیچ ئەندامێک تۆمار نەکراوە',
	'NO_POSTS'					=> 'بەشداری نییە',
	'NO_POSTS_TIME_FRAME'		=>  'هیچ پەیامێک بوونی نییە لەم بابەتە لە چوارچێوەی کاتی دیاریکراودا.',
	'NO_FEED_ENABLED'			=> 'Feed ـەکان چالاک نین لەم مەکۆیە.',
	'NO_FEED'					=> 'feed ـی چالاککراو ئامادە نییە.',
	'NO_STYLE_DATA'				=> 'نەتوانرا زانیاری دەربارەی ڕووکار بەدەست بگات',
	'NO_SUBJECT'				=>  'هیچ سەردێڕێک نەنووسراوە', 								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'گەڕانی دیاریکراو بوونی نییە.',
	'NO_SUPPORTED_AUTH_METHODS'	=>  'هیچ ڕێگایەک بۆ سەلماندن پاڵپشتی نەکراوە.',
	'NO_TOPIC'					=> 'بابەتی داواکراو بوونی نییە.',
	'NO_TOPIC_FORUM'			=>  'بابەت یان مەکۆ چیتر بوونی نییە.',
	'NO_TOPICS'					=> 'هیچ بابەت یان پەیامێک لەم مەکۆیەدا نییە.',
	'NO_TOPICS_TIME_FRAME'		=> 'هیچ بابەتێک بوونی نییە لەم مەکۆیە لە نێوان ماوەی دیاریکراود.',
	'NO_UNREAD_POSTS'			=> 'هیچ پەیامێکی نەخوێندراوە نییە',
	'NO_UPLOAD_FORM_FOUND'		=> 'بارکردن تەواوە بەڵام هیچ فۆڕمێکی بارکردنی گونجاو نەدۆزرایەوە.',
	'NO_USER'					=> 'بەکارهێنەری داواکراو بوونی نییە.',
	'NO_USERS'					=>  'بەکارهێنەرانی داواکراو بوونیان نییە.',
	'NO_USER_SPECIFIED'			=> 'هیچ ناوی بەکارهێنەرێک دیاریی نەکراوە.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d هاوپێچ',
		2	=> '%d هاوپێچ',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'هیچ پەیامێک لە چاوەڕوانییدا نییە.',		// 0
		1			=> '1 پەیام لە چاوەڕوانییدایە',		// 1
		2			=> '%d پەیام لە چاوەڕوانییدایە.',	// 2+
	),

	'OCCUPATION'				=> 'پیشە',
	'OFFLINE'					=> 'دەرهێڵ',
	'ONLINE'					=> 'سەرهێڵ',
	'ONLINE_BUDDIES'			=> 'هاوڕێ سەرهێڵەکان',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'لەسەرجەم بەکارهێنەران <strong>%1$d</strong> کەس لەسەر هێلن :: %2$s و %3$s',
		2	=> 'لەسەرجەم بەکارهێنەران <strong>%1$d</strong> کەس لەسەر هێلن :: %2$s و %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'لەسەرجەم بەکارهێنەران <strong>%1$d</strong> کەس لەسەر هێلن :: %2$s و %3$s',
		2	=> 'لەسەرجەم بەکارهێنەران <strong>%1$d</strong> کەس لەسەر هێلن :: %2$s و %3$s',
	),
	'OPTIONS'					=> 'هەڵبژاردنەکان',

	'PAGE_OF'				=> 'پەڕەی <strong>%1$d</strong> لە <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'پەڕە %s',
	'PASSWORD'				=> 'تێپەڕەوشە',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d ڕەهەند',
		2	=> '%d ڕەهەند',
	),
	'PLAY_QUICKTIME_FILE'	=> 'پەڕگەی Quicktime لێبدە',
	'PLEASE_WAIT'			=> 'تکایە چاوەڕێ بە.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'کرتە بکە بۆ بۆ بینینی ڕاپۆرت',
	'POSTING_MESSAGE'		=> 'ناردنی پەیام لە %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'ناردنی پەیامی تایبەت',
	'POST'					=> 'بەشداری',
	'POST_ANNOUNCEMENT'		=> 'ئاگەداری',
	'POST_STICKY'			=> 'جێگیر',
	'POSTED'				=> 'نێردراو',
	'POSTED_IN_FORUM'		=> 'لە',
	'POSTED_ON_DATE'		=> 'لە ڕێکەوتی',
	'POSTS'					=> 'بەشدارییەکان',
	'POSTS_UNAPPROVED'		=> 'لانی کەم پەیامێک لەم بابەتەدا پەسەند نەکراوە.',
	'POSTS_UNAPPROVED_FORUM'=> 'لانی کەم پەیامێک لەم مەکۆیەدا پەسەند نەکراوە.',
	'POST_BY_AUTHOR'		=> 'لەلایەن',
	'POST_BY_FOE'			=> 'ئەم پەیامە لەلایەن <strong>%1$s</strong> ـەوە نووسراوە کە هەنووکە لە لیستەی فەرامۆشکراوەکانتدایە. %2$ئەم پەیامە پیشان بدە%3$s',
	'POST_DISPLAY'			=> '%1$خستنەڕووی ئەم بەشدارییە%2$s.',
	'POST_DAY'				=> '%.2f پەیام لە ڕۆژێکدا',
	'POST_DELETED_ACTION'	=> 'بەشدارییە سڕاوەکان:',
	'POST_DELETED'			=> 'ئەم بەشدارییە سڕاوەتەوە.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> هەستا بەسڕینەوە بەشداری بەهۆی <strong>%1$s</strong> لە %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> هەستا بە سڕینەوەی بەشداری بەهۆی <strong>%1$s</strong> لە %3$s بەهۆی: %4$s',
	'POST_DETAILS'			=> 'وردەکارییەکانی پەیام',
	'POST_NEW_TOPIC'		=> 'بابەتی نوێ بنێرە',
	'POST_PCT'				=> '%.2f%% لە هەموو پەیامەکاندا',
	'POST_PCT_ACTIVE'		=> '%.2f%% لە پەیامەکانی بەکارهێنەردا',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% لە پەیامەکانی خۆتدا',
	'POST_REPLY'			=> 'وەڵامێک بنێرە',
	'POST_REPORTED'			=> 'کرتە بکە بۆ بینینی ئاگەداری',
	'POST_SUBJECT'			=> 'سەردێڕ بنووسە',
	'POST_TIME'				=> 'کاتی ناردن',
	'POST_TOPIC'			=> 'بابەتێکی نوێ ',
	'POST_UNAPPROVED_ACTION'	=> 'بەشداری لە چاوەڕێی پەسەندکردنە:',
	'POST_UNAPPROVED'		=> 'ئەم بەشدارییە تا ئێستا پەسەند نەکراوە.',
	'POWERED_BY'			=> 'Powered by %s',
	'PREVIEW'				=> 'پێشبینین',
	'PREVIOUS'				=> 'پێشوو',		// Used in pagination
	'PREVIOUS_STEP'			=> 'پێشوو',
	'PRIVACY'				=> 'تایبەتییەتی',
	'PRIVATE_MESSAGE'		=> 'پەیامی تایبەت',
	'PRIVATE_MESSAGES'		=> 'پەیامە تایبەتەکان',
	'PRIVATE_MESSAGING'		=> 'ناردنی پەیامی تایبەت',
	'PROFILE'				=> 'پەڕەی ئەندام',

	'QUICK_LINKS'			=> 'بەستەری خێرا',

	'RANK'						=> 'پلە',
	'READING_FORUM'				=> 'سەیری بابەتەکان دەکات لە %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'ڕاگەینداروی گشتی دەخوێنێتەوە',
	'READING_LINK'				=> 'دوای ئەم بەستەرە کەوتووە %s',
	'READING_TOPIC'				=> 'بابەت دەخوێنێتەوە لە %s',
	'READ_PROFILE'				=> 'پەڕەی تایبەتی',
	'REASON'					=> 'هۆکار',
	'RECORD_ONLINE_USERS'		=> 'زۆرترین بەکارهێنەر کە لەسەر هێڵ بوون لە یەک کاتدا بریتیبوو لە <strong>%1$s</strong> لە %2$s',
	'REDIRECT'					=> 'ئاڕاستەکردنەوە',
	'REDIRECTS'					=> 'سەرجەم ئاڕاستەکردنەوەکان',
	'REGISTER'					=> 'خۆتۆمارکردن',
	'REGISTERED_USERS'			=> 'بەکارهێنەرە خۆتۆمارکردووەکانی سەرهێڵ',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'لە ئێستادا %1$d ئەندام هەیە و  %2$s لەسەرهێلن',
		2	=> 'لە ئێستادا %1$d ئەندام هەیە و  %2$s لەسەرهێلن',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d ئەندام',
		2	=> '%d ئەندام',
	),
	'REMOVE'					=> 'سڕینەوە',
	'REMOVE_INSTALL'			=> 'تکایە پێش بەکارهێنانی مەکۆ بوخچەی install بسڕەوە، بگوازەوە یان ناوی بگۆڕە. گەر بوخچەکە هەر هەیە، تەنها دەتوانیت پەڕەی بەڕێوەبەر ببینیت.',
	'REPLIES'					=> 'وەڵامەکان',
	'REPLY_WITH_QUOTE'			=> 'وەڵام لەگەل دەق کردن',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'وەڵامدانەوەی ڕاگەیندراوە گشتییەکان',
	'REPLYING_MESSAGE'			=> 'وەڵام دانەوەی پەیام لە %s',
	'REPORT_BY'					=> 'ئاگەداری لەلایەن',
	'REPORT_POST'				=> 'هۆشداریدان لەم بەشدارییە',
	'REPORTING_POST'			=> 'هۆشداریدانی بەشداری',
	'RESEND_ACTIVATION'			=> 'دوبارە پۆستی ئەلیکترۆنی چاڵاککردن بنێرەوە',
	'RESET'						=> 'بەتاڵکردنەوە',
	'RESTORE_PERMISSIONS'		=> 'گێڕادنەوەی دەسەڵاتەکان',
	'RETURN_INDEX'				=> '%sبگەڕێوە بۆ پەڕەی دەستپێک%s',
	'RETURN_FORUM'				=> '%sبگەڕێوە بۆ مەکۆی بابەت%s',
	'RETURN_PAGE'				=> '%sبگەڕێوە بۆ پەڕەی پێشوو%s',
	'RETURN_TOPIC'				=>  '%sبگەڕێوە بۆ دوا بابەتی سەردانکراو%s',
	'RETURN_TO'					=> 'گەڕاندنەوەی بۆ “%s”',
	'RETURN_TO_INDEX'			=> 'گەڕانەوە بۆ دەستپێک',
	'FEED'						=> 'Feed',
	'FEED_NEWS'					=> 'هەواڵ',
	'FEED_TOPICS_ACTIVE'		=> 'بابەتە چالاکەکان',
	'FEED_TOPICS_NEW'			=> 'بابەتە نوێیەکان',
	'RULES_ATTACH_CAN'			=> '<strong>دەتوانیت</strong> هاوپێچ بنێریت لەم مەکۆیە',
	'RULES_ATTACH_CANNOT'		=> '<strong>ناتوانیت</strong> هاوپێچ بنێریت لەم مەکۆیە',
	'RULES_DELETE_CAN'			=> '<strong>دەتوانیت</strong> پەیامەکانت بسڕیتەوە لەم مەکۆیە',
	'RULES_DELETE_CANNOT'		=> '<strong>ناتوانیت</strong> پەیامەکانت بسڕیتەوە لەم مەکۆیە',
	'RULES_DOWNLOAD_CAN'		=> '<strong>دەتوانیت</strong> هاوپێچەکان دابگریت لەم مەکۆیە',
	'RULES_DOWNLOAD_CANNOT'		=> '<strong>ناتوانیت</strong> هاوپێچەکان دابگریت لەم مەکۆیە',
	'RULES_EDIT_CAN'			=> '<strong>دەتوانیت</strong> دەستکاری پەیامەکانت بکەیت لەم مەکۆیە',
	'RULES_EDIT_CANNOT'			=> '<strong>ناتوانیت</strong> دەستکاری پەیامەکانت بکەیت لەم مەکۆیە',
	'RULES_LOCK_CAN'			=> '<strong>دەتوانیت</strong> بابەتەکانت دابخەیت لەم مەکۆیە',
	'RULES_LOCK_CANNOT'			=>  '<strong>ناتوانیت</strong> بابەتەکانت دابخەیت لەم مەکۆیە',
	'RULES_POST_CAN'			=> '<strong>دەتوانیت</strong> بابەتی نوێ بنێریت لەم مەکۆیە',
	'RULES_POST_CANNOT'			=>  '<strong>ناتوانیت</strong> بابەتی نوێ بنێریت لەم مەکۆیە',
	'RULES_REPLY_CAN'			=> '<strong>دەتوانیت</strong> وەڵامی بابەتەکان بدەیتەوە لەم مەکۆیە',
	'RULES_REPLY_CANNOT'		=>  '<strong>ناتوانیت</strong> وەڵامی بابەتەکان بدەیتەوە لەم مەکۆیە',
	'RULES_VOTE_CAN'			=> '<strong>دەتوانیت</strong> دەنگ بدەیت لە ڕاپرسییەکان لەم مەکۆیە','<strong>ناتوانیت</strong> دەنگ بدەیت لە ڕاپرسییەکان لەم مەکۆیە','You <strong>cannot</strong> vote in polls in this forum',

	'SEARCH'					=> 'گەڕان',
	'SEARCH_MINI'				=> 'گەڕان…',
	'SEARCH_ADV'				=> 'گەڕانی پەرەسەندوو',
	'SEARCH_ADV_EXPLAIN'		=> 'بینینی هەڵبژاردنە پەرەسەندووەکانی گەڕان ',
	'SEARCH_KEYWORDS'			=> 'گەڕان لە کلیلە ووشە',
	'SEARCHING_FORUMS'			=> 'گەڕان لە مەکۆکان',
	'SEARCH_ACTIVE_TOPICS'		=> 'گەڕان لە بابەتە چاڵاکەکان',
	'SEARCH_FOR'				=> 'گەڕان بەدوای',
	'SEARCH_FORUM'				=> 'لەم مەکۆیە دا بگەڕێ…',
	'SEARCH_NEW'				=> 'بەشداری نوێ',
	'SEARCH_POSTS_BY'			=> 'گەڕان لە بەشدارییەکان بەپێی',
	'SEARCH_SELF'				=> 'بەشدارییەکانت',
	'SEARCH_TOPIC'				=> 'لەم بابەتە دا بگەڕێ…',
	'SEARCH_UNANSWERED'			=> 'بەشدارییە وەڵام نەدراوەکان',
	'SEARCH_UNREAD'				=> 'بەشدارییە نەخوێندراوەکان',
	'SEARCH_USER_POSTS'			=> 'گەڕان لە بەشدارییەکانی ئەندام',
	'SECONDS'					=> 'چرکە',
	'SEE_ALL'					=> 'هەموو ببینە',
	'SELECT'					=> 'دیاریکردن',
	'SELECT_ALL_CODE'			=> 'دیاریکردنی هەموو',
	'SELECT_DESTINATION_FORUM'	=> 'تکایە مەکۆیەکی مەبەست دیار بکە',
	'SELECT_FORUM'				=> 'مەکۆیەک دیار بکە',
	'SEND_EMAIL'				=> 'ناردنی پەیامی ئەلیکترۆنی',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'پەیامێکی ئەلیکترۆنی بنێرە بۆ %s',
	'SEND_PRIVATE_MESSAGE'		=> 'ناردنی پەیامی تایبەتی',
	'SETTINGS'					=> 'ڕێکخستنەکان',
	'SIGNATURE'					=> 'واژۆ',
	'SKIP'						=> 'بیپەڕێنە بۆ ناوەڕۆک',
	'SKYPE'						=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> ' ڕاژەکار پاڵپشتی سەلماندن ناکات.',
	'SORRY_AUTH_READ'			=> 'ڕێت پێ نەدراوە ئەم مەکۆیە ببینیت.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'ڕێت پێ نەدراوە بە داگرتنی ئەم هاوپێچە',
	'SORT_BY'					=>'ڕیزکردن بە پێی',
	'SORT_JOINED'				=> 'ڕێکەوتی بەشداربوون',
	'SORT_LOCATION'				=> 'شوێن',
	'SORT_RANK'					=> 'پلە',
	'SORT_POSTS'				=> 'پەیامەکان',
	'SORT_TOPIC_TITLE'			=> 'ناونیشانی بابەت',
	'SORT_USERNAME'				=> 'ناوی بەکارهێنەر',
	'SPLIT_TOPIC'				=> 'بەشکردنی بابەت',
	'SQL_ERROR_OCCURRED'		=>  'هەڵەیەکی SQL ڕوویدا لە کاتی کردنەوەی ئەم پەڕەیەدا. تکایە پەیوەندی بە %sBoard Administrator%s وە بکە گەر ئەم هەڵەیە بەردەوام بوو.',
	'STATISTICS'				=> 'ئامارەکان',
	'START_WATCHING_FORUM'		=> 'بەشداربوون لە مەکۆ',
	'START_WATCHING_TOPIC'		=> 'بەشداربوون لە بابەت',
	'STOP_WATCHING_FORUM'		=> 'بەشدارنەبوون لە مەکۆ',
	'STOP_WATCHING_TOPIC'		=> 'بەشدارنەبوون لە بابەت',
	'STRING_LIST_MULTI'			=> '%1$s, and %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s and %2$s',
	'SUBFORUM'					=> 'ژێرمەکۆ',
	'SUBFORUMS'					=> 'ژێرمەکۆکان',
	'SUBJECT'					=> 'سەردێڕ',
	'SUBMIT'					=> 'ناردن',

	'TB'				=> 'تێرابایت',
	'TERMS_USE'			=> 'مەرجەکانی بەکارهێنان',
	'TEST_CONNECTION'	=> 'تاقیکردنەوەی پەیوەندی',
	'THE_TEAM'			=> 'دەستەی بەڕێوەبەران',
	'TIB'				=> 'TiB',
	'TIME'				=> 'کات',
	'TIMEOUT_PROCESSING_REQ'			=> 'ماوەی داواکردن تەواو بوو.',

	'TOO_LARGE'						=> 'بەهای نووسراو زۆر گەورەیە',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'ڕێکخستنی نووسراو زۆر گەورەیە <strong>زۆرترین ژمارە لە وەرگری ڕێپێدراو لەهەر پەیامێکی تایبەت</strong> بەهای',

	'TOO_LONG'						=>  'ئەو نرخەی نووسیوتە زۆر درێژە.',

	'TOO_LONG_CONFIRM_CODE'			=> 'ئەو کۆدە دڵنیابوونەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_DATEFORMAT'			=> ' شێوازی ئەو کاتەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_JABBER'				=> ' ناوی ئەو هەژمارە جابەرەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_NEW_PASSWORD'			=> 'ئەو تێپەڕەوشەیەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_PASSWORD_CONFIRM'		=>  'ئەو تێپەڕەوشە دڵنیابوونەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_USER_PASSWORD'		=> 'ئەو تێپەڕە ووشەیەی نووسیوتە زۆر درێژە.',
	'TOO_LONG_USERNAME'				=> 'ناوی بەکارهێنەری نووسراو زۆر درێژە.',
	'TOO_LONG_EMAIL'				=> 'پۆستی ئەلیکترۆنی نووسراو زۆر درێژە.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'هەوڵت دا دەنگ بە زیاتر لە یەک هەڵبژاردن بدەیت.',

	'TOO_SHORT'						=> 'ئەو نرخەی دیاریت کردووە زۆر کورتە.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'ئەو کۆدی دڵنیابوونەی لێتداوە زۆر کورتە.',
	'TOO_SHORT_DATEFORMAT'			=> ' شێوازی ئەو ڕێکەوتەی نووسیوتە زۆر کورتە.',
	'TOO_SHORT_JABBER'				=>  ' ناوی ئەو هەژمارە جابەرەی نووسیوتە زۆر کورتە.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'ئەو تێپەڕەوشەیەی نووسیوتە زۆر کورتە.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'ئەو تێپەڕەوشە دڵنیابوونەی نووسیوتە زۆر کورتە.',
	'TOO_SHORT_USER_PASSWORD'		=> 'ئەو تێپەڕە ووشەیەی نووسیوتە زۆر کورتە.',
	'TOO_SHORT_USERNAME'			=> 'ناوی بەکارهێنەری نووسراو زۆر کورتە.',
	'TOO_SHORT_EMAIL'				=>  'پۆستی ئەلیکترۆنی نووسراو زۆر کورتە.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'پۆستی ئەلیکترۆنی دڵنیابوونەوە زۆر کورتە.',
	'TOO_SMALL'						=> 'ئەو نرخەی دیاریت کردووە زۆر کورتە.',
	'TOO_SMALL_MAX_RECIPIENTS'		=>'ڕێکخستنی نووسراو زۆر بچووکە<strong>زۆرترین ژمارە لە وەرگری ڕێپێدراو لەهەر پەیامێکی تایبەت</strong> بەهای',

	'TOPIC'				=> 'بابەت',
	'TOPICS'			=> 'بابەتەکان',
	'TOPICS_UNAPPROVED'	=> 'بە لانی کەمەوە بابەتێک لەم مەکۆیە پەسەند نەکراوە.',
	'TOPIC_ICON'		=> 'وێنۆچکەی بابەت',
	'TOPIC_LOCKED'		=> 'ئەم بابەتە داخراوە، ناتوانیت دەستکاری پەیامەکان و وەڵامەکانی تر بکەیت.',
	'TOPIC_LOCKED_SHORT'=> 'بابەت داخراوە',
	'TOPIC_MOVED'		=> 'بابەت گواستراوەتەوە',
	'TOPIC_REVIEW'		=> 'پێداچوونەوەی بابەت',
	'TOPIC_TITLE'		=> 'سەردێڕی بابەت',
	'TOPIC_UNAPPROVED'	=> 'ئەم بابەتە پەسەند نەکراوە',
	'TOPIC_DELETED'		=> 'ئەم بابەتە سڕاوەتەوە ',
	'TOTAL_ATTACHMENTS'	=> 'هاوپێچ(ەکان)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d تۆمار',
		2	=> '%d تۆمارەکان',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d پەیامی تایبەتی لەسەرجەم پەیامەکان',
		2	=> '%dپەیامی تایبەتی لەسەرجەم پەیامەکان',
	),
	'TOPIC_POLL'		=> 'ئەم بابەتە ڕاپرسی لەگەل دایە.',
	'TOTAL_POSTS'		=> 'سەرجەم بەشدارییەکان',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'سەرجەم بەشدارییەکان <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'ئەم بابەتە ئاگەدارکراوەتەوە',
	'TOTAL_TOPICS'		=> array(
		2	=> 'سەرجەم بابەتەکان <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'سەرجەم ئەندامان <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=>  'هەلەکانی شوێن پێ هەڵگرتنی PHP: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'نەتوانرا دوورییەکانی وێنە بپێورێت.',
	'UNABLE_TO_DELIVER_FILE'=>  'نەتوانرا پەڕگە بەدەست بگەیەنرێت.',
	'UNKNOWN_BROWSER'		=> 'وێبگەڕێکی نەزانراو',
	'UNMARK_ALL'			=> 'لابردنی نیشانەی هەمووی',
	'UNREAD_MESSAGES'		=> 'پەیامە نەخوێندراوەکان',
	'UNREAD_POST'			=> 'بەشداری نەخوێندراو',
	'UNREAD_POSTS'			=> 'بەشدارییە نەخوێندراوەکان',
	'UNWATCH_FORUM_CONFIRM'		=> 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت هاوبەشیکردنت ڕابگیریت لەگەل ئەم مەکۆیە ؟',
	'UNWATCH_FORUM_DETAILED'	=> 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت هاوبەشیکردنت ڕابگیریت لەگەل مەکۆی “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت هاوبەشیکردنت ڕابگیریت لەگەل ئەم بابەتە?',
	'UNWATCH_TOPIC_DETAILED'	=> 'ئایە تۆ دڵنیایت لەوەی کە دەتەوێت هاوبەشیکردنت ڕابگیریت لەگەل بابەتی “%s”?',
	'UNWATCHED_FORUMS'			=> 'چیتر بەشدار نیت لە مەکۆ دیاریکراوەکاندا.',
	'UNWATCHED_TOPICS'			=> 'چیتر بەشدار نیت لە بابەتە دیاریکراوەکاندا.',
	'UNWATCHED_FORUMS_TOPICS'	=>  'چیتر بەشدار نیت لە یەکە دیاریکراوەکاندا.',
	'UPDATE'				=> 'نوێکردنەوە',
	'UPLOAD_IN_PROGRESS'	=>  'بارکردن لە پرۆسەی جێ بەجێکردن دایە',
	'URL_REDIRECT'			=> 'گەر وێبگەڕەکەت پاڵپشتی گواستنەوە ناکات %sتکایە کرتە لێرە بکە تا بگوازرێیتەوە%s.',
	'USERGROUPS'			=> 'گرووپەکان',
	'USERNAME'				=> 'ناوی بەکارهێنەر',
	'USERNAMES'				=> 'ناوی بەکارهێنەران',
	'USER_AVATAR'			=> 'وێنۆچکەی بەکارهێنەر',
	'USER_CANNOT_READ'		=> 'ناتوانیت پەیامەکانی ئەم مەکۆیە بخوێنیتەوە.',
	'USER_POSTS'			=> array(
		1	=> '%d بەشداری',
		2	=> '%d بەشداری',
	),
	'USERS'					=> 'ئەندامان',
	'USE_PERMISSIONS'		=> 'دەسەڵاتەکانی بەکارهێنەر تاقی بکەوە',

	'USER_NEW_PERMISSION_DISALLOWED'	=>  'ببورە، ڕێت پێ نەداوە بۆ بەکارهێنانی ئەم تایبەتمەندییە. لەوانەیە تەنها خۆت تۆمار کردبێت لێرە و پێویستت بە بەشداری زۆرتر بێت تا بتوانیت ئەم تایبەتمەندییە بەکار ببەییت.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'بینرا',
	'VIEWED_COUNTS'		=> array(
		0	=> 'تا ئێستا نەبینراوە',
		1	=> ' %d جار بینراوە',
		2	=> ' %d جار بینراوە',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'سەیری پەڕەی پەیوەندی بە بەڕێوەبەران دەکات',
	'VIEWING_FAQ'				=> 'سەیری پ.هـ.د دەکات',
	'VIEWING_MEMBERS'			=> 'سەیری وردەکارییەکانی ئەندام دەکات',
	'VIEWING_ONLINE'			=> 'سەیری ئامادەبوانی ئێستا دەکات',
	'VIEWING_MCP'				=> 'سەیری پەڕەی چاودێر دەکات',
	'VIEWING_MEMBER_PROFILE'	=> 'سەیری پەڕەی ئەندام دەکات',
	'VIEWING_PRIVATE_MESSAGES'	=> 'سەیری پەیامە تایبەتییەکان دەکات',
	'VIEWING_REGISTER'			=> 'تۆمارکردنی هەژمار',
	'VIEWING_UCP'				=> 'خستنەڕووی پەڕەی بەکارهێنەر',
	'VIEWS'						=> 'خستنەڕوو',
	'VIEW_BOOKMARKS'			=> 'خستنەڕووی دڵخوازەکان',
	'VIEW_FORUM_LOGS'			=> 'خستنەڕووی تۆمارەکان',
	'VIEW_LATEST_POST'			=> 'خستنەڕووی دوایین بەشداری',
	'VIEW_NEWEST_POST'			=> 'خستنەڕووی یەکەم بەشداری نەخوێندراو',
	'VIEW_NOTES'				=> 'خستنەڕووی سەرنجەکانی بەکارهێنەر',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'ئەم زانیاریانە بەپێی ئەندامە چاڵاکەکانی ماوەی  %d خولەکی ڕابردووە',
		2	=> 'ئەم زانیاریانە بەپێی ئەندامە چاڵاکەکانی ماوەی %d خولەکی ڕابردووە',
	),
	'VIEW_TOPIC'				=> 'خستنەڕووی بابەت',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'ڕاگەیاندن: ',
	'VIEW_TOPIC_GLOBAL'			=> 'ڕاگەیاندنی گشتی: ',
	'VIEW_TOPIC_LOCKED'			=> 'داخراوە: ',
	'VIEW_TOPIC_LOGS'			=> 'خستنەڕووی تۆمارەکان',
	'VIEW_TOPIC_MOVED'			=> 'گواستراوەتەوە: ',
	'VIEW_TOPIC_POLL'			=> 'ڕاپرسی: ',
	'VIEW_TOPIC_STICKY'			=> 'جێگیرکراو: ',
	'VISIT_WEBSITE'				=> 'سەردانکردنی وێبگە',

	'WARNINGS'			=> 'ئاگەدارییەکان',
	'WARN_USER'			=> 'ئاگەدارکردنەوەی ئەندام',
	'WATCH_FORUM_CONFIRM'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم مەکۆیە ؟',
	'WATCH_FORUM_DETAILED'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم مەکۆیە “%s”؟',
	'WATCH_TOPIC_CONFIRM'	=> 'ئایە تۆ دڵنیایت لە بەشداری کردنی ئەم بابەتە؟',
	'WATCH_TOPIC_DETAILED'	=> 'ئایە تۆ دڵنیایت لە بەشداریکردنی ئەم بابەتە “%s”؟',
	'WELCOME_SUBJECT'	=> 'بەخێربێت بەڕێز %s ',
	'WEBSITE'			=> 'وێبگە',
	'WHOIS'				=> 'کێیە',
	'WHO_IS_ONLINE'		=> 'ئامادەبوانی ئێستا',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	=> 'تێپەڕەووشەی هەلەت نووسیوە',

	'WRONG_DATA_COLOUR'			=> 'بەهای ئەو ڕەنگەی نوسویتە تەواو نییە.',
	'WRONG_DATA_JABBER'			=> 'ئەو ناوەی نوسیوتە دروست نییە لە هەژماری Jabber.',
	'WRONG_DATA_LANG'			=> 'زمانی هەلبژێرداراو تەواو نییە.',
	'WRONG_DATA_POST_SD'		=> 'ڕێڕەوی ڕێکخستنی بەشدارییەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_POST_SK'		=> 'هەلبژاردنی ڕێکخستنی بەشدارییەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_TOPIC_SD'		=> 'ڕێڕەوی ڕێکخستنی بابەتەکان کە دیارت کردبوو دروست نییە.',
	'WRONG_DATA_TOPIC_SK'		=> 'هەلبژاردنی ڕێکخستنی بابەتەکان کە دیارت کردبوو دروست نییە.',
	'WROTE'						=> 'نووسی',

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'				=> 'ساڵ',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> 'بەلێ',
	'YOU_LAST_VISIT'	=> 'دوایین سەرەدانت: %s',

	'datetime'			=> array(
		'TODAY'		=> 'ئەمڕۆ',
		'TOMORROW'	=> 'سبەی',
		'YESTERDAY'	=> 'دوێنی',
		'AGO'		=> array(
			0		=> 'کەمتر لە خولەکێک لەمەوبەر',
			1		=> '%d خولەک لەمەوبەر',
			2		=> '%d خولەک لەمەوبەر',
		),

		'Sunday'	=> 'یەک شەممە',
		'Monday'	=> 'دوو شەممە',
		'Tuesday'	=> 'سێ شەممە',
		'Wednesday'	=> 'چوار شەممە',
		'Thursday'	=> 'پێنج شەممە',
		'Friday'	=> 'هەینی',
		'Saturday'	=> ' شەممە',

		'Sun'		=> 'یەک شەممە',
		'Mon'		=> 'دوو شەممە',
		'Tue'		=> 'سێ شەممە',
		'Wed'		=> 'چوارشەممە',
		'Thu'		=> 'پێنچ شەممە',
		'Fri'		=> 'هەینی',
		'Sat'		=> 'شەممە',

		'January'	=> 'کانونی دووەم',
		'February'	=> 'شوبات',
		'March'		=> 'ئازار',
		'April'		=> 'نیسان',
		'May'		=> 'ئایار',
		'June'		=> 'حوزەیران',
		'July'		=> 'تەمموز',
		'August'	=> 'ئاب',
		'September' => 'ئەیلول',
		'October'	=> 'تشرینی یەکەم',
		'November'	=> 'تشرینی دووەم',
		'December'	=> 'کانونی یەکەم',

		'Jan'		=> 'کانونی دووەم',
		'Feb'		=> 'شوبات',
		'Mar'		=> 'ئازار',
		'Apr'		=> 'نیسان',
		'May_short'	=> 'ئایار',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'حوزەیران',
		'Jul'		=> 'تەمموز',
		'Aug'		=> 'ئاب',
		'Sep'		=> 'ئەیلول',
		'Oct'		=> 'تشرینی یەکەم',
		'Nov'		=> 'تشرینی دووەم',
		'Dec'		=> 'کانونی یەکەم',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'ئەفریقا/Abidjan'	=> 'ئەفریقا/Abidjan',
		'ئەفریقا/Accra'		=> 'ئەفریقا/Accra',
		'ئەفریقا/Addis_Ababa'	=> 'ئەفریقا/Addis Ababa',
		'ئەفریقا/Algiers'	=> 'ئەفریقا/Algiers',
		'ئەفریقا/Asmara'		=> 'ئەفریقا/Asmara',
		'ئەفریقا/Bamako'		=> 'ئەفریقا/Bamako',
		'ئەفریقا/Bangui'		=> 'ئەفریقا/Bangui',
		'ئەفریقا/Banjul'		=> 'ئەفریقا/Banjul',
		'ئەفریقا/Bissau'		=> 'ئەفریقا/Bissau',
		'ئەفریقا/Blantyre'	=> 'ئەفریقا/Blantyre',
		'ئەفریقا/Brazzaville'	=> 'ئەفریقا/Brazzaville',
		'ئەفریقا/Bujumbura'	=> 'ئەفریقا/Bujumbura',
		'ئەفریقا/Cairo'		=> 'ئەفریقا/Cairo',
		'ئەفریقا/Casablanca'	=> 'ئەفریقا/Casablanca',
		'ئەفریقا/Ceuta'		=> 'ئەفریقا/Ceuta',
		'ئەفریقا/Conakry'	=> 'ئەفریقا/Conakry',
		'ئەفریقا/Dakar'		=> 'ئەفریقا/Dakar',
		'ئەفریقا/Dar_es_Salaam'	=> 'ئەفریقا/Dar es Salaam',
		'ئەفریقا/Djibouti'	=> 'ئەفریقا/Djibouti',
		'ئەفریقا/Douala'		=> 'ئەفریقا/Douala',
		'ئەفریقا/El_Aaiun'	=> 'ئەفریقا/El Aaiun',
		'ئەفریقا/Freetown'	=> 'ئەفریقا/Freetown',
		'ئەفریقا/Gaborone'	=> 'ئەفریقا/Gaborone',
		'ئەفریقا/Harare'		=> 'ئەفریقا/Harare',
		'ئەفریقا/Johannesburg'	=> 'ئەفریقا/Johannesburg',
		'ئەفریقا/Juba'		=> 'ئەفریقا/Juba',
		'ئەفریقا/Kampala'	=> 'ئەفریقا/Kampala',
		'ئەفریقا/Khartoum'	=> 'ئەفریقا/Khartoum',
		'ئەفریقا/Kigali'		=> 'ئەفریقا/Kigali',
		'ئەفریقا/Kinshasa'	=> 'ئەفریقا/Kinshasa',
		'ئەفریقا/Lagos'		=> 'ئەفریقا/Lagos',
		'ئەفریقا/Libreville'	=> 'ئەفریقا/Libreville',
		'ئەفریقا/Lome'		=> 'ئەفریقا/Lome',
		'ئەفریقا/Luanda'		=> 'ئەفریقا/Luanda',
		'ئەفریقا/Lubumbashi'	=> 'ئەفریقا/Lubumbashi',
		'ئەفریقا/Lusaka'		=> 'ئەفریقا/Lusaka',
		'ئەفریقا/Malabo'		=> 'ئەفریقا/Malabo',
		'ئەفریقا/Maputo'		=> 'ئەفریقا/Maputo',
		'ئەفریقا/Maseru'		=> 'ئەفریقا/Maseru',
		'ئەفریقا/Mbabane'	=> 'ئەفریقا/Mbabane',
		'ئەفریقا/Mogadishu'	=> 'ئەفریقا/Mogadishu',
		'ئەفریقا/Monrovia'	=> 'ئەفریقا/Monrovia',
		'ئەفریقا/Nairobi'	=> 'ئەفریقا/Nairobi',
		'ئەفریقا/Ndjamena'	=> 'ئەفریقا/Ndjamena',
		'ئەفریقا/Niamey'		=> 'ئەفریقا/Niamey',
		'ئەفریقا/Nouakchott'	=> 'ئەفریقا/Nouakchott',
		'ئەفریقا/Ouagadougou'	=> 'ئەفریقا/Ouagadougou',
		'ئەفریقا/Porto-Novo'	=> 'ئەفریقا/Porto-Novo',
		'ئەفریقا/Sao_Tome'	=> 'ئەفریقا/Sao Tome',
		'ئەفریقا/Tripoli'	=> 'ئەفریقا/Tripoli',
		'ئەفریقا/Tunis'		=> 'ئەفریقا/Tunis',
		'ئەفریقا/Windhoek'	=> 'ئەفریقا/Windhoek',

		'ئەمریکا/Adak'		=> 'ئەمریکا/Adak',
		'ئەمریکا/Anchorage'	=> 'ئەمریکا/Anchorage',
		'ئەمریکا/Anguilla'	=> 'ئەمریکا/Anguilla',
		'ئەمریکا/Antigua'	=> 'ئەمریکا/Antigua',
		'ئەمریکا/Araguaina'	=> 'ئەمریکا/Araguaina',

		'ئەمریکا/Argentina/Buenos_Aires'	=> 'ئەمریکا/Argentina/Buenos Aires',
		'ئەمریکا/Argentina/Catamarca'	=> 'ئەمریکا/Argentina/Catamarca',
		'ئەمریکا/Argentina/Cordoba'		=> 'ئەمریکا/Argentina/Cordoba',
		'ئەمریکا/Argentina/Jujuy'		=> 'ئەمریکا/Argentina/Jujuy',
		'ئەمریکا/Argentina/La_Rioja'	=> 'ئەمریکا/Argentina/La Rioja',
		'ئەمریکا/Argentina/Mendoza'		=> 'ئەمریکا/Argentina/Mendoza',
		'ئەمریکا/Argentina/Rio_Gallegos'	=> 'ئەمریکا/Argentina/Rio Gallegos',
		'ئەمریکا/Argentina/Salta'		=> 'ئەمریکا/Argentina/Salta',
		'ئەمریکا/Argentina/San_Juan'	=> 'ئەمریکا/Argentina/San Juan',
		'ئەمریکا/Argentina/San_Luis'	=> 'ئەمریکا/Argentina/San Luis',
		'ئەمریکا/Argentina/Tucuman'		=> 'ئەمریکا/Argentina/Tucuman',
		'ئەمریکا/Argentina/Ushuaia'		=> 'ئەمریکا/Argentina/Ushuaia',

		'ئەمریکا/Aruba'			=> 'ئەمریکا/Aruba',
		'ئەمریکا/Asuncion'		=> 'ئەمریکا/Asuncion',
		'ئەمریکا/Atikokan'		=> 'ئەمریکا/Atikokan',
		'ئەمریکا/Bahia'			=> 'ئەمریکا/Bahia',
		'ئەمریکا/Bahia_Banderas'	=> 'ئەمریکا/Bahia Banderas',
		'ئەمریکا/Barbados'		=> 'ئەمریکا/Barbados',
		'ئەمریکا/Belem'			=> 'ئەمریکا/Belem',
		'ئەمریکا/Belize'		=> 'ئەمریکا/Belize',
		'ئەمریکا/Blanc-Sablon'	=> 'ئەمریکا/Blanc-Sablon',
		'ئەمریکا/Boa_Vista'		=> 'ئەمریکا/Boa Vista',
		'ئەمریکا/Bogota'		=> 'ئەمریکا/Bogota',
		'ئەمریکا/Boise'			=> 'ئەمریکا/Boise',
		'ئەمریکا/Cambridge_Bay'	=> 'ئەمریکا/Cambridge Bay',
		'ئەمریکا/Campo_Grande'	=> 'ئەمریکا/Campo Grande',
		'ئەمریکا/Cancun'		=> 'ئەمریکا/Cancun',
		'ئەمریکا/Caracas'		=> 'ئەمریکا/Caracas',
		'ئەمریکا/Cayenne'		=> 'ئەمریکا/Cayenne',
		'ئەمریکا/Cayman'		=> 'ئەمریکا/Cayman',
		'ئەمریکا/Chicago'		=> 'ئەمریکا/Chicago',
		'ئەمریکا/Chihuahua'		=> 'ئەمریکا/Chihuahua',
		'ئەمریکا/Costa_Rica'	=> 'ئەمریکا/Costa Rica',
		'ئەمریکا/Creston'		=> 'ئەمریکا/Creston',
		'ئەمریکا/Cuiaba'		=> 'ئەمریکا/Cuiaba',
		'ئەمریکا/Curacao'		=> 'ئەمریکا/Curacao',
		'ئەمریکا/Danmarkshavn'	=> 'ئەمریکا/Danmarkshavn',
		'ئەمریکا/Dawson'		=> 'ئەمریکا/Dawson',
		'ئەمریکا/Dawson_Creek'	=> 'ئەمریکا/Dawson Creek',
		'ئەمریکا/Denver'		=> 'ئەمریکا/Denver',
		'ئەمریکا/Detroit'		=> 'ئەمریکا/Detroit',
		'ئەمریکا/Dominica'		=> 'ئەمریکا/Dominica',
		'ئەمریکا/Edmonton'		=> 'ئەمریکا/Edmonton',
		'ئەمریکا/Eirunepe'		=> 'ئەمریکا/Eirunepe',
		'ئەمریکا/El_Salvador'	=> 'ئەمریکا/El Salvador',
		'ئەمریکا/Fortaleza'		=> 'ئەمریکا/Fortaleza',
		'ئەمریکا/Glace_Bay'		=> 'ئەمریکا/Glace Bay',
		'ئەمریکا/Godthab'		=> 'ئەمریکا/Godthab',
		'ئەمریکا/Goose_Bay'		=> 'ئەمریکا/Goose Bay',
		'ئەمریکا/Grand_Turk'	=> 'ئەمریکا/Grand Turk',
		'ئەمریکا/Grenada'		=> 'ئەمریکا/Grenada',
		'ئەمریکا/Guadeloupe'	=> 'ئەمریکا/Guadeloupe',
		'ئەمریکا/Guatemala'		=> 'ئەمریکا/Guatemala',
		'ئەمریکا/Guayaquil'		=> 'ئەمریکا/Guayaquil',
		'ئەمریکا/Guyana'		=> 'ئەمریکا/Guyana',
		'ئەمریکا/Halifax'		=> 'ئەمریکا/Halifax',
		'ئەمریکا/Havana'		=> 'ئەمریکا/Havana',
		'ئەمریکا/Hermosillo'		=> 'ئەمریکا/Hermosillo',
		'ئەمریکا/هیندستانa/هیندستانapolis'	=> 'ئەمریکا/هیندستانa/هیندستانapolis',
		'ئەمریکا/هیندستانa/Knox'		=> 'ئەمریکا/هیندستانa/Knox',
		'ئەمریکا/هیندستانa/Marengo'	=> 'ئەمریکا/هیندستانa/Marengo',
		'ئەمریکا/هیندستانa/Petersburg'	=> 'ئەمریکا/هیندستانa/Petersburg',
		'ئەمریکا/هیندستانa/Tell_City'	=> 'ئەمریکا/هیندستانa/Tell City',
		'ئەمریکا/هیندستانa/Vevay'		=> 'ئەمریکا/هیندستانa/Vevay',
		'ئەمریکا/هیندستانa/Vincennes'	=> 'ئەمریکا/هیندستانa/Vincennes',
		'ئەمریکا/هیندستانa/Winamac'	=> 'ئەمریکا/هیندستانa/Winamac',
		'ئەمریکا/Inuvik'		=> 'ئەمریکا/Inuvik',
		'ئەمریکا/Iqaluit'		=> 'ئەمریکا/Iqaluit',
		'ئەمریکا/Jamaica'		=> 'ئەمریکا/Jamaica',
		'ئەمریکا/Juneau'		=> 'ئەمریکا/Juneau',
		'ئەمریکا/Kentucky/Louisville'	=> 'ئەمریکا/Kentucky/Louisville',
		'ئەمریکا/Kentucky/Monticello'	=> 'ئەمریکا/Kentucky/Monticello',
		'ئەمریکا/Kralendijk'	=> 'ئەمریکا/Kralendijk',
		'ئەمریکا/La_Paz'		=> 'ئەمریکا/La Paz',
		'ئەمریکا/Lima'			=> 'ئەمریکا/Lima',
		'ئەمریکا/Los_Angeles'	=> 'ئەمریکا/Los Angeles',
		'ئەمریکا/Lower_Princes'	=> 'ئەمریکا/Lower Princes',
		'ئەمریکا/Maceio'		=> 'ئەمریکا/Maceio',
		'ئەمریکا/Managua'		=> 'ئەمریکا/Managua',
		'ئەمریکا/Manaus'		=> 'ئەمریکا/Manaus',
		'ئەمریکا/Marigot'		=> 'ئەمریکا/Marigot',
		'ئەمریکا/Martinique'	=> 'ئەمریکا/Martinique',
		'ئەمریکا/Matamoros'		=> 'ئەمریکا/Matamoros',
		'ئەمریکا/Mazatlan'		=> 'ئەمریکا/Mazatlan',
		'ئەمریکا/Menominee'		=> 'ئەمریکا/Menominee',
		'ئەمریکا/Merida'		=> 'ئەمریکا/Merida',
		'ئەمریکا/Metlakatla'	=> 'ئەمریکا/Metlakatla',
		'ئەمریکا/Mexico_City'	=> 'ئەمریکا/Mexico City',
		'ئەمریکا/Miquelon'		=> 'ئەمریکا/Miquelon',
		'ئەمریکا/Moncton'		=> 'ئەمریکا/Moncton',
		'ئەمریکا/Monterrey'		=> 'ئەمریکا/Monterrey',
		'ئەمریکا/Montevideo'	=> 'ئەمریکا/Montevideo',
		'ئەمریکا/Montreal'		=> 'ئەمریکا/Montreal',
		'ئەمریکا/Montserrat'	=> 'ئەمریکا/Montserrat',
		'ئەمریکا/Nassau'		=> 'ئەمریکا/Nassau',
		'ئەمریکا/New_York'		=> 'ئەمریکا/New York',
		'ئەمریکا/Nipigon'		=> 'ئەمریکا/Nipigon',
		'ئەمریکا/Nome'			=> 'ئەمریکا/Nome',
		'ئەمریکا/Noronha'		=> 'ئەمریکا/Noronha',
		'ئەمریکا/North_Dakota/Beulah'		=> 'ئەمریکا/North Dakota/Beulah',
		'ئەمریکا/North_Dakota/Center'		=> 'ئەمریکا/North Dakota/Center',
		'ئەمریکا/North_Dakota/New_Salem'	=> 'ئەمریکا/North Dakota/New Salem',
		'ئەمریکا/Ojinaga'		=> 'ئەمریکا/Ojinaga',
		'ئەمریکا/Panama'		=> 'ئەمریکا/Panama',
		'ئەمریکا/Pangnirtung'	=> 'ئەمریکا/Pangnirtung',
		'ئەمریکا/Paramaribo'	=> 'ئەمریکا/Paramaribo',
		'ئەمریکا/Phoenix'		=> 'ئەمریکا/Phoenix',
		'ئەمریکا/Port-au-Prince'	=> 'ئەمریکا/Port-au-Prince',
		'ئەمریکا/Port_of_Spain'	=> 'ئەمریکا/Port of Spain',
		'ئەمریکا/Porto_Velho'	=> 'ئەمریکا/Porto Velho',
		'ئەمریکا/Puerto_Rico'	=> 'ئەمریکا/Puerto Rico',
		'ئەمریکا/Rainy_River'	=> 'ئەمریکا/Rainy River',
		'ئەمریکا/Rankin_Inlet'	=> 'ئەمریکا/Rankin Inlet',
		'ئەمریکا/Recife'		=> 'ئەمریکا/Recife',
		'ئەمریکا/Regina'		=> 'ئەمریکا/Regina',
		'ئەمریکا/Resolute'		=> 'ئەمریکا/Resolute',
		'ئەمریکا/Rio_Branco'	=> 'ئەمریکا/Rio Branco',
		'ئەمریکا/Santa_Isabel'	=> 'ئەمریکا/Santa Isabel',
		'ئەمریکا/Santarem'		=> 'ئەمریکا/Santarem',
		'ئەمریکا/Santiago'		=> 'ئەمریکا/Santiago',
		'ئەمریکا/Santo_Domingo'	=> 'ئەمریکا/Santo Domingo',
		'ئەمریکا/Sao_Paulo'		=> 'ئەمریکا/Sao Paulo',
		'ئەمریکا/Scoresbysund'	=> 'ئەمریکا/Scoresbysund',
		'ئەمریکا/Shiprock'		=> 'ئەمریکا/Shiprock',
		'ئەمریکا/Sitka'			=> 'ئەمریکا/Sitka',
		'ئەمریکا/St_Barthelemy'	=> 'ئەمریکا/St. Barthelemy',
		'ئەمریکا/St_Johns'		=> 'ئەمریکا/St. Johns',
		'ئەمریکا/St_Kitts'		=> 'ئەمریکا/St. Kitts',
		'ئەمریکا/St_Lucia'		=> 'ئەمریکا/St. Lucia',
		'ئەمریکا/St_Thomas'		=> 'ئەمریکا/St. Thomas',
		'ئەمریکا/St_Vincent'	=> 'ئەمریکا/St. Vincent',
		'ئەمریکا/Swift_Current'	=> 'ئەمریکا/Swift Current',
		'ئەمریکا/Tegucigalpa'	=> 'ئەمریکا/Tegucigalpa',
		'ئەمریکا/Thule'			=> 'ئەمریکا/Thule',
		'ئەمریکا/Thunder_Bay'	=> 'ئەمریکا/Thunder Bay',
		'ئەمریکا/Tijuana'		=> 'ئەمریکا/Tijuana',
		'ئەمریکا/Toronto'		=> 'ئەمریکا/Toronto',
		'ئەمریکا/Tortola'		=> 'ئەمریکا/Tortola',
		'ئەمریکا/Vancouver'		=> 'ئەمریکا/Vancouver',
		'ئەمریکا/Whitehorse'	=> 'ئەمریکا/Whitehorse',
		'ئەمریکا/Winnipeg'		=> 'ئەمریکا/Winnipeg',
		'ئەمریکا/Yakutat'		=> 'ئەمریکا/Yakutat',
		'ئەمریکا/Yellowknife'	=> 'ئەمریکا/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'ئاسیا/Aden'			=> 'ئاسیا/Aden',
		'ئاسیا/Almaty'		=> 'ئاسیا/Almaty',
		'ئاسیا/Amman'		=> 'ئاسیا/Amman',
		'ئاسیا/Anadyr'		=> 'ئاسیا/Anadyr',
		'ئاسیا/Aqtau'		=> 'ئاسیا/Aqtau',
		'ئاسیا/Aqtobe'		=> 'ئاسیا/Aqtobe',
		'ئاسیا/Ashgabat'		=> 'ئاسیا/Ashgabat',
		'ئاسیا/Baghdad'		=> 'ئاسیا/Baghdad',
		'ئاسیا/Bahrain'		=> 'ئاسیا/Bahrain',
		'ئاسیا/Baku'			=> 'ئاسیا/Baku',
		'ئاسیا/Bangkok'		=> 'ئاسیا/Bangkok',
		'ئاسیا/Beirut'		=> 'ئاسیا/Beirut',
		'ئاسیا/Bishkek'		=> 'ئاسیا/Bishkek',
		'ئاسیا/Brunei'		=> 'ئاسیا/Brunei',
		'ئاسیا/Choibalsan'	=> 'ئاسیا/Choibalsan',
		'ئاسیا/Chongqing'	=> 'ئاسیا/Chongqing',
		'ئاسیا/Colombo'		=> 'ئاسیا/Colombo',
		'ئاسیا/Damascus'		=> 'ئاسیا/Damascus',
		'ئاسیا/Dhaka'		=> 'ئاسیا/Dhaka',
		'ئاسیا/Dili'			=> 'ئاسیا/Dili',
		'ئاسیا/Dubai'		=> 'ئاسیا/Dubai',
		'ئاسیا/Dushanbe'		=> 'ئاسیا/Dushanbe',
		'ئاسیا/Gaza'			=> 'ئاسیا/Gaza',
		'ئاسیا/Harbin'		=> 'ئاسیا/Harbin',
		'ئاسیا/Hebron'		=> 'ئاسیا/Hebron',
		'ئاسیا/Ho_Chi_Minh'	=> 'ئاسیا/Ho Chi Minh',
		'ئاسیا/Hong_Kong'	=> 'ئاسیا/Hong Kong',
		'ئاسیا/Hovd'			=> 'ئاسیا/Hovd',
		'ئاسیا/Irkutsk'		=> 'ئاسیا/Irkutsk',
		'ئاسیا/Jakarta'		=> 'ئاسیا/Jakarta',
		'ئاسیا/Jayapura'		=> 'ئاسیا/Jayapura',
		'ئاسیا/Jerusalem'	=> 'ئاسیا/Jerusalem',
		'ئاسیا/Kabul'		=> 'ئاسیا/Kabul',
		'ئاسیا/Kamchatka'	=> 'ئاسیا/Kamchatka',
		'ئاسیا/Karachi'		=> 'ئاسیا/Karachi',
		'ئاسیا/Kashgar'		=> 'ئاسیا/Kashgar',
		'ئاسیا/Kathmandu'	=> 'ئاسیا/Kathmandu',
		'ئاسیا/Khandyga'		=> 'ئاسیا/Khandyga',
		'ئاسیا/Kolkata'		=> 'ئاسیا/Kolkata',
		'ئاسیا/Krasnoyarsk'	=> 'ئاسیا/Krasnoyarsk',
		'ئاسیا/Kuala_Lumpur'	=> 'ئاسیا/Kuala Lumpur',
		'ئاسیا/Kuching'		=> 'ئاسیا/Kuching',
		'ئاسیا/Kuwait'		=> 'ئاسیا/Kuwait',
		'ئاسیا/Macau'		=> 'ئاسیا/Macau',
		'ئاسیا/Magadan'		=> 'ئاسیا/Magadan',
		'ئاسیا/Makassar'		=> 'ئاسیا/Makassar',
		'ئاسیا/Manila'		=> 'ئاسیا/Manila',
		'ئاسیا/Muscat'		=> 'ئاسیا/Muscat',
		'ئاسیا/Nicosia'		=> 'ئاسیا/Nicosia',
		'ئاسیا/Novokuznetsk'	=> 'ئاسیا/Novokuznetsk',
		'ئاسیا/Novosibirsk'	=> 'ئاسیا/Novosibirsk',
		'ئاسیا/Omsk'			=> 'ئاسیا/Omsk',
		'ئاسیا/Oral'			=> 'ئاسیا/Oral',
		'ئاسیا/Phnom_Penh'	=> 'ئاسیا/Phnom Penh',
		'ئاسیا/Pontianak'	=> 'ئاسیا/Pontianak',
		'ئاسیا/Pyongyang'	=> 'ئاسیا/Pyongyang',
		'ئاسیا/Qatar'		=> 'ئاسیا/Qatar',
		'ئاسیا/Qyzylorda'	=> 'ئاسیا/Qyzylorda',
		'ئاسیا/Rangoon'		=> 'ئاسیا/Rangoon',
		'ئاسیا/Riyadh'		=> 'ئاسیا/Riyadh',
		'ئاسیا/Sakhalin'		=> 'ئاسیا/Sakhalin',
		'ئاسیا/Samarkand'	=> 'ئاسیا/Samarkand',
		'ئاسیا/Seoul'		=> 'ئاسیا/Seoul',
		'ئاسیا/Shanghai'		=> 'ئاسیا/Shanghai',
		'ئاسیا/Singapore'	=> 'ئاسیا/Singapore',
		'ئاسیا/Taipei'		=> 'ئاسیا/Taipei',
		'ئاسیا/Tashkent'		=> 'ئاسیا/Tashkent',
		'ئاسیا/Tbilisi'		=> 'ئاسیا/Tbilisi',
		'ئاسیا/Tehran'		=> 'ئاسیا/Tehran',
		'ئاسیا/Thimphu'		=> 'ئاسیا/Thimphu',
		'ئاسیا/Tokyo'		=> 'ئاسیا/Tokyo',
		'ئاسیا/Ulaanbaatar'	=> 'ئاسیا/Ulaanbaatar',
		'ئاسیا/Urumqi'		=> 'ئاسیا/Urumqi',
		'ئاسیا/Ust-Nera'		=> 'ئاسیا/Ust-Nera',
		'ئاسیا/Vientiane'	=> 'ئاسیا/Vientiane',
		'ئاسیا/Vladivostok'	=> 'ئاسیا/Vladivostok',
		'ئاسیا/Yakutsk'		=> 'ئاسیا/Yakutsk',
		'ئاسیا/Yekaterinburg'	=> 'ئاسیا/Yekaterinburg',
		'ئاسیا/Yerevan'		=> 'ئاسیا/Yerevan',

		'ئەتلانتیک/Azores'		=> 'ئەتلانتیک/Azores',
		'ئەتلانتیک/Bermuda'		=> 'ئەتلانتیک/Bermuda',
		'ئەتلانتیک/Canary'		=> 'ئەتلانتیک/Canary',
		'ئەتلانتیک/Cape_Verde'	=> 'ئەتلانتیک/Cape Verde',
		'ئەتلانتیک/Faroe'		=> 'ئەتلانتیک/Faroe',
		'ئەتلانتیک/Madeira'		=> 'ئەتلانتیک/Madeira',
		'ئەتلانتیک/Reykjavik'	=> 'ئەتلانتیک/Reykjavik',
		'ئەتلانتیک/South_Georgia'	=> 'ئەتلانتیک/South Georgia',
		'ئەتلانتیک/St_Helena'	=> 'ئەتلانتیک/St. Helena',
		'ئەتلانتیک/Stanley'		=> 'ئەتلانتیک/Stanley',

		'ئوسترالیا/Adelaide'	=> 'ئوسترالیا/Adelaide',
		'ئوسترالیا/Brisbane'	=> 'ئوسترالیا/Brisbane',
		'ئوسترالیا/Broken_Hill'	=> 'ئوسترالیا/Broken Hill',
		'ئوسترالیا/Currie'		=> 'ئوسترالیا/Currie',
		'ئوسترالیا/Darwin'		=> 'ئوسترالیا/Darwin',
		'ئوسترالیا/Eucla'		=> 'ئوسترالیا/Eucla',
		'ئوسترالیا/Hobart'		=> 'ئوسترالیا/Hobart',
		'ئوسترالیا/Lindeman'	=> 'ئوسترالیا/Lindeman',
		'ئوسترالیا/Lord_Howe'	=> 'ئوسترالیا/Lord Howe',
		'ئوسترالیا/Melbourne'	=> 'ئوسترالیا/Melbourne',
		'ئوسترالیا/Perth'		=> 'ئوسترالیا/Perth',
		'ئوسترالیا/Sydney'		=> 'ئوسترالیا/Sydney',

		'ئەوروپا/Amsterdam'	=> 'ئەوروپا/Amsterdam',
		'ئەوروپا/Andorra'	=> 'ئەوروپا/Andorra',
		'ئەوروپا/Athens'		=> 'ئەوروپا/Athens',
		'ئەوروپا/Belgrade'	=> 'ئەوروپا/Belgrade',
		'ئەوروپا/Berlin'		=> 'ئەوروپا/Berlin',
		'ئەوروپا/Bratislava'	=> 'ئەوروپا/Bratislava',
		'ئەوروپا/Brussels'	=> 'ئەوروپا/Brussels',
		'ئەوروپا/Bucharest'	=> 'ئەوروپا/Bucharest',
		'ئەوروپا/Budapest'	=> 'ئەوروپا/Budapest',
		'ئەوروپا/Busingen'	=> 'ئەوروپا/Busingen',
		'ئەوروپا/Chisinau'	=> 'ئەوروپا/Chisinau',
		'ئەوروپا/Copenhagen'	=> 'ئەوروپا/Copenhagen',
		'ئەوروپا/Dublin'		=> 'ئەوروپا/Dublin',
		'ئەوروپا/Gibraltar'	=> 'ئەوروپا/Gibraltar',
		'ئەوروپا/Guernsey'	=> 'ئەوروپا/Guernsey',
		'ئەوروپا/Helsinki'	=> 'ئەوروپا/Helsinki',
		'ئەوروپا/Isle_of_Man'	=> 'ئەوروپا/Isle of Man',
		'ئەوروپا/Istanbul'	=> 'ئەوروپا/Istanbul',
		'ئەوروپا/Jersey'		=> 'ئەوروپا/Jersey',
		'ئەوروپا/Kaliningrad'	=> 'ئەوروپا/Kaliningrad',
		'ئەوروپا/Kiev'		=> 'ئەوروپا/Kiev',
		'ئەوروپا/Lisbon'		=> 'ئەوروپا/Lisbon',
		'ئەوروپا/Ljubljana'	=> 'ئەوروپا/Ljubljana',
		'ئەوروپا/London'		=> 'ئەوروپا/London',
		'ئەوروپا/Luxembourg'	=> 'ئەوروپا/Luxembourg',
		'ئەوروپا/Madrid'		=> 'ئەوروپا/Madrid',
		'ئەوروپا/Malta'		=> 'ئەوروپا/Malta',
		'ئەوروپا/Mariehamn'	=> 'ئەوروپا/Mariehamn',
		'ئەوروپا/Minsk'		=> 'ئەوروپا/Minsk',
		'ئەوروپا/Monaco'		=> 'ئەوروپا/Monaco',
		'ئەوروپا/Moscow'		=> 'ئەوروپا/Moscow',
		'ئەوروپا/Oslo'		=> 'ئەوروپا/Oslo',
		'ئەوروپا/Paris'		=> 'ئەوروپا/Paris',
		'ئەوروپا/Podgorica'	=> 'ئەوروپا/Podgorica',
		'ئەوروپا/Prague'		=> 'ئەوروپا/Prague',
		'ئەوروپا/Riga'		=> 'ئەوروپا/Riga',
		'ئەوروپا/Rome'		=> 'ئەوروپا/Rome',
		'ئەوروپا/Samara'		=> 'ئەوروپا/Samara',
		'ئەوروپا/San_Marino'	=> 'ئەوروپا/San Marino',
		'ئەوروپا/Sarajevo'	=> 'ئەوروپا/Sarajevo',
		'ئەوروپا/Simferopol'	=> 'ئەوروپا/Simferopol',
		'ئەوروپا/Skopje'		=> 'ئەوروپا/Skopje',
		'ئەوروپا/Sofia'		=> 'ئەوروپا/Sofia',
		'ئەوروپا/Stockholm'	=> 'ئەوروپا/Stockholm',
		'ئەوروپا/Tallinn'	=> 'ئەوروپا/Tallinn',
		'ئەوروپا/Tirane'		=> 'ئەوروپا/Tirane',
		'ئەوروپا/Uzhgorod'	=> 'ئەوروپا/Uzhgorod',
		'ئەوروپا/Vaduz'		=> 'ئەوروپا/Vaduz',
		'ئەوروپا/Vatican'	=> 'ئەوروپا/Vatican',
		'ئەوروپا/Vienna'		=> 'ئەوروپا/Vienna',
		'ئەوروپا/Vilnius'	=> 'ئەوروپا/Vilnius',
		'ئەوروپا/Volgograd'	=> 'ئەوروپا/Volgograd',
		'ئەوروپا/Warsaw'		=> 'ئەوروپا/Warsaw',
		'ئەوروپا/Zagreb'		=> 'ئەوروپا/Zagreb',
		'ئەوروپا/Zaporozhye'	=> 'ئەوروپا/Zaporozhye',
		'ئەوروپا/Zurich'		=> 'ئەوروپا/Zurich',

		'هیندستان/Antananarivo'	=> 'هیندستان/Antananarivo',
		'هیندستان/Chagos'		=> 'هیندستان/Chagos',
		'هیندستان/Christmas'	=> 'هیندستان/Christmas',
		'هیندستان/Cocos'		=> 'هیندستان/Cocos',
		'هیندستان/Comoro'		=> 'هیندستان/Comoro',
		'هیندستان/Kerguelen'	=> 'هیندستان/Kerguelen',
		'هیندستان/Mahe'		=> 'هیندستان/Mahe',
		'هیندستان/Maldives'	=> 'هیندستان/Maldives',
		'هیندستان/Mauritius'	=> 'هیندستان/Mauritius',
		'هیندستان/Mayotte'	=> 'هیندستان/Mayotte',
		'هیندستان/Reunion'	=> 'هیندستان/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'				=> '01 Jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
